### ISSUE TITLE
SuperiorSkyblock2 wont compatible with WildTools

### ISSUE THREAD

**Issue by ItzFabb-uwu** [BG-Software-LLC/WildTools#100]
### Minecraft's Version

This server is running Paper version git-Paper-"e7d928a" (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
You are 8 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-"91f3eda" (MC: 1.18.1)

### Plugin's Version

1.9.0 b576 SuperiorSkyblock2

### Describe the bug

Whenever i give myself an tools from wildtools superiorskyblock2 throwing a bunch of error, and also this occur everytime i gave myself the items

### To Reproduce

./tools give name trench_pickaxe 1
./is create name

Try mine a block using trench pickaxe!

### Additional Information

ill send you a video one moment!

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the errors

**Comment by ItzFabb-uwu** [comment]
okay

**Comment by ItzFabb-uwu** [comment]
its fixed now
