### ISSUE TITLE
Cant open chest or crafting table etc...

### ISSUE THREAD

**Issue by SkytraceXLSU** [BG-Software-LLC/WildTools#103]
### Minecraft's Version

Paper(317) 1.18.2-R0.1-SNAPSHOT

### Plugin's Version

WildTools-2.12.0-b59

### Describe the bug

We cant open chest or Frurnace crafting table etc when we have a wildtools items 

### To Reproduce

Create a wild tools items and click on a chest with this in hand

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
Do you have any errors by any chance?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
> Hello @OmerBenGera,
> 
> I come with some news about this "bug".
> 
> The problem appear when we have the `auto-collect` or when the `tool-mode` is HARVESTER.
> 
> We don't have any error or message, just we can't use any block (butons, chests ....)
> 
> Thank you very much !
> 
> This is an example item with the bug
> 
> ```
>   harvester_hoe1:
>     tool-mode: HARVESTER
>     glow: true
>     radius: 1
>     auto-collect: true
>     type: WOODEN_HOE
>     unbreakable: true
>     name: '&e&l⚡&r&b&kSKY&r_&3H&b&kOU&r&3E&r&c.ini&r&e&l⚡'
> ```

You can't use the blocks while holding the tool?

**Comment by Teyir** [comment]
Yes, I can't use anything when I have the tool in my hand

**Comment by Teyir** [comment]
> > Hello @OmerBenGera,
> > 
> > I come with some news about this "bug".
> > 
> > The problem appear when we have the `auto-collect` or when the `tool-mode` is HARVESTER.
> > 
> > We don't have any error or message, just we can't use any block (butons, chests ....)
> > 
> > Thank you very much !
> > 
> > This is an example item with the bug
> > 
> > ```
> >   harvester_hoe1:
> >     tool-mode: HARVESTER
> >     glow: true
> >     radius: 1
> >     auto-collect: true
> >     type: WOODEN_HOE
> >     unbreakable: true
> >     name: '&e&l⚡&r&b&kSKY&r_&3H&b&kOU&r&3E&r&c.ini&r&e&l⚡'
> > ```
> 
> You can't use the blocks while holding the tool?

Or in my second hand

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
When holding a tool in the off hand, I can interact with blocks normally.
If I hold trench pickaxe with auto-collect, I can interact with blocks as well. When I hold a harvester hoe, it doesn't work but it's intended - the tool has another use when right clicking it - it will harvest all nearby blocks.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Teyir** [comment]
> Any news regarding this?

Hello,

We have the same problem...

**Comment by OmerBenGera** [comment]
> > Any news regarding this?
> 
> Hello,
> 
> We have the same problem...

Are you able to replicate the issue on a server with only WildTools installed?
As I told you already, I can't replicate it myself.

**Comment by Teyir** [comment]
Yes I can replicate the issue on a 1.19 paper server with just wildtools

**Comment by OmerBenGera** [comment]
> Yes I can replicate the issue on a 1.19 paper server with just wildtools

Any errors?

**Comment by OmerBenGera** [comment]
> Yes I can replicate the issue on a 1.19 paper server with just wildtools

Take a video showcasing the issue.
Upload it to an online streaming (such as youtube) and send a link to it here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
