### ISSUE TITLE
Problem support upgradeablespawners

### ISSUE THREAD

**Issue by D3BoxOfficiel** [BG-Software-LLC/WildTools#105]
### Minecraft's Version

1.16.5

### Plugin's Version

2.12.0.57

### Describe the bug

Double the rendered spawners (1 wildstacker spawn and 1 upgreadeable spawner) and I would like it to be the upgreadeablespawner one that drops

### To Reproduce

just use crowbar (wildtools) on spawners upgreadeablespawners

### Additional Information

https://gyazo.com/c999ac03ac68bd9c588a0c75ed78f0cc

**Comment by OmerBenGera** [comment]
UpgradeableSpawners should add support for WildTools.
They can do that using the API of the plugin
