### ISSUE TITLE
Items going invisible if thrown.

### ISSUE THREAD

**Issue by moonies44** [BG-Software-LLC/WildTools#106]
### Minecraft's Version

1.17.1 paper

### Plugin's Version

WildTools-2.12.0-b59.jar

### Describe the bug

When using plugins that stack items on the floor (such as rosestacker), the items go invisible when dropped. video was provided in discord but it won't me post it here due to file size. upon booting up the server it works fine then after about 10 minutes the bug starts to be reproducable. 

### To Reproduce

install a item stacking plugin.
throw wands (in my case builder wand) out of your inventory with Q 
item is now invisible on the floor, but actually still exists and can be picked up.

**Comment by OmerBenGera** [comment]
I tested it without any stacking plugin and with WildStacker and both worked.
Does it works as intended without the stacking plugins for you as well?

**Comment by moonies44** [comment]
> I tested it without any stacking plugin and with WildStacker and both worked. Does it works as intended without the stacking plugins for you as well?

Correct, without stacking plugins it works fine without any problems at all. but for some reason when the server fresh reboots with a stacking plugin it works and then the bug starts to begin 10~ minutes runtime in. can provide server ip for you to try yourself if need be. (server is in development, so i won't post it publicly)

**Comment by moonies44** [comment]
Sorry, its now happening with another plugin, meaning it must be an issue with stacking plugins. i will mark as resolved for now - as the dev for the stacking plugin lead me to believe it wasn't their plugin when infact it was. thank you.

**Comment by OmerBenGera** [comment]
> Sorry, its now happening with another plugin, meaning it must be an issue with stacking plugins. i will mark as resolved for now - as the dev for the stacking plugin lead me to believe it wasn't their plugin when infact it was. thank you.

Wanted to tell you that it's probably an issue with the stacking plugins if it works fine without them and with WildStacker, which has a stacking system as well :)
