### ISSUE TITLE
Error when mining stacked blocks from superiorskyblock2

### ISSUE THREAD

**Issue by CayeOficial** [BG-Software-LLC/WildTools#109]
### Minecraft's Version

1.16 airplane

### Plugin's Version

Dev #60 

### Describe the bug

If you break a blacklisted block, which is stacked by superiorskyblock2 with a 3x3 pickaxe, it shows this error on console:
https://paste.md-5.net/isusohapuj.md

### To Reproduce

Stack a block using superiorskyblock2
break it

**Comment by OmerBenGera** [comment]
Duplicate of #108
