### ISSUE TITLE
Harvester Hoe turns grass blocks (and dirt) into spawners

### ISSUE THREAD

**Issue by konfix** [BG-Software-LLC/WildTools#117]
### Minecraft's Version

Purpur [paper fork] v1702 (latest) 1.19

### Plugin's Version

WildTools (2.13.0)

### Describe the bug

Harvester Hoes can turn grass blocks and dirt blocks into pig spawners. This is a really concerning issue because players can get unlimited amounts of spawners very easily.

Temporary solution is to blacklist grass blocks and dirt blocks in the configuration, but I'm still not sure if other blocks can be turned into spawners as well.

### To Reproduce

Click on grass or dirt block using harvester hoes.

### Additional Information

![unknown](https://user-images.githubusercontent.com/66477781/177754237-79e20e7e-5e87-423a-803b-ed9f1fb18b8a.png)

**Comment by OmerBenGera** [comment]
Why would harvester hoes turn blocks into spawners in first place?
It sounds like another plugin conflicts with WildTools.

Are you able to replicate the issue on a server with only WildTools installed?

**Comment by konfix** [comment]
> Why would harvester hoes turn blocks into spawners in first place? It sounds like another plugin conflicts with WildTools.
> 
> Are you able to replicate the issue on a server with only WildTools installed?

I'm afraid that's not the case. It happens with WildTools alone on 1.19 (not tested on older versions)

![unknown](https://user-images.githubusercontent.com/66477781/178085053-d8d5475c-b17e-460f-90b7-47d5eda95e8a.png)

**Comment by konfix** [comment]
Just to confirm, it only happens when you hold the harvester hoe item. Not any hoe.

**Comment by Pix3lPirat3** [comment]
My guess is that this snippet is returning the wrong ID somehow perhaps? (I haven't tested this myself)
https://github.com/BG-Software-LLC/WildTools/blob/58a5725c2cf985f20999cf8ed6e44522ece9e84c/src/main/java/com/bgsoftware/wildtools/objects/tools/WHarvesterTool.java#L189

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
