### ISSUE TITLE
ShopGUI+ API has been Changed

### ISSUE THREAD

**Issue by klaidosHka** [BG-Software-LLC/WildTools#121]
### Minecraft's Version

1.16.5

### Plugin's Version

Latest

### Describe the bug

Class Not Found Exceptions after interracting with SellWand

### To Reproduce

Use latest ShopGUI+ and latest WildTools, get SellWand, try to sell something in the chest.

### Additional Information

https://github.com/brcdev-minecraft/shopgui-api/releases/tag/3.0.0

**Comment by OmerBenGera** [comment]
Downgrade SGP for now

**Comment by klaidosHka** [comment]
Alright, I guess I will try to. Updated it yesterday from wayyy lower version, because quite stupid (for a shop) bug was found X_X, I hope it will still be fixed in one version behind latest one. Haha... Welp, if something, I will just wait for your update, it's not something that is required in a super hurry, at least for me.

**Comment by klaidosHka** [comment]
Downgraded ShopGUI+ version doesn't load players data from database for some reason and keeps throwing errors regarding that...  And WildTools have another error now, wrong Object types used around `PricesProvider_ShopGUIPlus.java:57` So, I guess, I will stick to the upper version, where shop is usable at least 😁.

**Comment by OmerBenGera** [comment]
Added in latest dev build
