### ISSUE TITLE
Uses of Magnet Wand not decreasing on usage

### ISSUE THREAD

**Issue by LeftCrosz** [BG-Software-LLC/WildTools#123]
### Minecraft's Version

TacoSpigot 1.8.8

### Plugin's Version

3.8.0 #323

### Describe the bug

When having WildStacker's item stacking enabled (3.7.0 or 3.8.0), the uses of the magnet wand does not decrease on usage.
When having Wildstacker's item stacking disabled, the uses of the magnet wand does decrease on usage.
The main problem of Wildstacker is that if the item stacking of wildstacker is enabled, then the issue occurs. If it don't, then the issue won't occur.

### To Reproduce

Get WildStacker's item stacking 3.8.0 enabled, use the magnet wand to pickup items on ground.
https://user-images.githubusercontent.com/40970486/182015904-0a22aacb-5fc5-496e-99b0-fbf784ae606a.mp4

**Comment by OmerBenGera** [comment]
You must be in Survival mode in order to have your uses / durability of your tools to decrease.
I tested it out in Survival and it worked fine for me.

**Comment by LeftCrosz** [comment]
I tested with Survival Mode. You need to have WildStacker's Item Stacking enabled aswell.
https://user-images.githubusercontent.com/40970486/182832599-21e06a5d-3670-41d0-a5f5-082d263c87b1.mp4

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
