### ISSUE TITLE
CUBOID mode soul sand glitch

### ISSUE THREAD

**Issue by JHarris12345** [BG-Software-LLC/WildTools#124]
### Minecraft's Version

1.17.1

### Plugin's Version

2.11.0-DEVb23

### Describe the bug

If you have a bubble column above soul sand, and break the soul sand with a cuboid tool, the bubble column effect is still there even though the soul sand gets broken

### To Reproduce

1) Make a bubble colum
2) Mine soul sand with cuboid tool
3) Bubbles still there and work

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
What version of the game are you using?

**Comment by JHarris12345** [comment]
1.17.1

**Comment by OmerBenGera** [comment]
> 1.17.1

The exact output of /version please

**Comment by JHarris12345** [comment]
Ok let's forget this issue then because I can work around it if you fix another issue. Putting WATER or LAVA in the blacklist for cuboid tools doesn't stop water or lava being removed. It's like it doesn't care for it at all. If you mine a block next to water or lava, it will still remove it. If this is fixed, I can fix the other issue

**Comment by JHarris12345** [comment]
Because you can make this glitch:

https://gyazo.com/dd1ab0571269e6c464f592a0976b1fc7

Notice how the bubbles are still going above where you can see water has been removed by the cuboid tool. The bubbles shouldn't be able to be above that

**Comment by OmerBenGera** [comment]
@JHarris12345 Check out latest dev build, let me know if it fixes both issues (water being removed as well as bubbles still occur when they shouldn't)

Btw, if you wanted to blacklist the water, you should have used "BUBBLE_COLUMN", as bubbled water blocks are a different block type in minecraft.

**Comment by JHarris12345** [comment]
Loading it I get this:

[20:27:03 INFO]: [WildTools] Error while loading adapter - your version mappings are not supported... Please contact @Ome_R

Version:
This server is running Pufferfish version git-Pufferfish-22 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 42ef3dc on HEAD)
Received invalid status code (404) from server.
Previous version: git-Airplane-110 (MC: 1.17.1)

**Comment by OmerBenGera** [comment]
> Reference in new is

Update to latest version of 1.17.1

**Comment by JHarris12345** [comment]
I can't update any further. That seems to be the latest pufferfish 1.17 version

**Comment by OmerBenGera** [comment]
> I can't update any further. That seems to be the latest pufferfish 1.17 version

Check out latest dev build now, should work

**Comment by JHarris12345** [comment]
All works perfect thanks!

**Comment by OmerBenGera** [comment]
Great, glad to hear :)

**Comment by JHarris12345** [comment]
> Great, glad to hear :)

In this new version, cuboid tools don't remove liquids at all even if they aren't blacklisted

**Comment by OmerBenGera** [comment]
> > Great, glad to hear :)
> 
> In this new version, cuboid tools don't remove liquids at all even if they aren't blacklisted

Thats intended.
You cant remove liquids in vanilla using a pickaxe as well
