### ISSUE TITLE
Plugin fails with "does not support your version mappings" (MC1.19 Paper e4f21e3)

### ISSUE THREAD

**Issue by Beanzilla** [BG-Software-LLC/WildTools#126]
### Minecraft's Version

Paper version git-Paper-60 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e4f21e3)

paper.jar

### Plugin's Version

v2.4.1.69 (Yes dev)

### Describe the bug

Plugin fails on startup with:
```
Error while loading adapter - your version mappings are not supported... Please contact @Ome_R
```

### To Reproduce

N/A (I just grabbed the plugin and dropped it into an existing setup)

### Additional Information

Please see Issue [#577](https://github.com/BG-Software-LLC/WildStacker/issues/577).

> I'll stop making issues for WildLoader too (since I think you get the point, they all don't seem to work right)

**Comment by OmerBenGera** [comment]
1.19 is not supported, update to 1.19.1

**Comment by Beanzilla** [comment]
Yup, upgraded to 1.19.1 and plugins work fine, thank you.
