### ISSUE TITLE
Problem with explosive pickaxe

### ISSUE THREAD

**Issue by EagL3-GIT** [BG-Software-LLC/WildTools#129]
### Minecraft's Version

1.19 (build 81)

### Plugin's Version

2.13.1.80

### Describe the bug

Its spamming a lot of warns by using explosive pickaxe.
https://pastebin.com/WnvreXYV

### To Reproduce

Just give urself an explosive pickaxe and break some blocks.

**Comment by OmerBenGera** [comment]
Version of spigot that you're using?

**Comment by EagL3-GIT** [comment]
I recently updated to 1.19.2 but the problem is still there.

This server is running Paper version git-Paper-135 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: eff22eb)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-81 (MC: 1.19)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
