### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by LeichterPanzer** [BG-Software-LLC/WildTools#130]
### Minecraft's Version

1.19.2 Paper , latest stable build

### Plugin's Version

2022.7

### Describe the bug

I cant write any commands like /wildtools give in the chat , nothing is getting shown or is working

### To Reproduce

Enter /wildtools in the chat

**Comment by OmerBenGera** [comment]
Update the plugin to latest dev build

**Comment by LeichterPanzer** [comment]
> Update the plugin to latest dev build

I did and it still doesnt work

**Comment by OmerBenGera** [comment]
> > Update the plugin to latest dev build
> 
> I did and it still doesnt work

Look for errors from when the plugin was loaded, upload them to pastebin and send them here.

**Comment by LeichterPanzer** [comment]
> > > Update the plugin to latest dev build
> > 
> > 
> > I did and it still doesnt work
> 
> Look for errors from when the plugin was loaded, upload them to pastebin and send them here.

I just pasted the entire log https://pastebin.com/QqmL9BNy

**Comment by OmerBenGera** [comment]
> > > > Update the plugin to latest dev build
> > > 
> > > 
> > > I did and it still doesnt work
> > 
> > 
> > Look for errors from when the plugin was loaded, upload them to pastebin and send them here.
> 
> I just pasted the entire log https://pastebin.com/QqmL9BNy

There are no errors at all. Are you sure you have permissions to use `/tools`?

**Comment by LeichterPanzer** [comment]
> > > > > Update the plugin to latest dev build
> > > > 
> > > > 
> > > > I did and it still doesnt work
> > > 
> > > 
> > > Look for errors from when the plugin was loaded, upload them to pastebin and send them here.
> > 
> > 
> > I just pasted the entire log https://pastebin.com/QqmL9BNy
> 
> There are no errors at all. Are you sure you have permissions to use `/tools`?

I always used /wildtools
