### ISSUE TITLE
The Harvester how doesn't work on soul sand, only on farmlands

### ISSUE THREAD

**Issue by SpadaccinoNero7** [BG-Software-LLC/WildTools#131]
### Minecraft's Version

server papermc 1.19.2

### Plugin's Version

2022.7

### Describe the bug

When i use the harvester hoe on the farmland it works but when i use it on the soul sand for the nether wart it won't work

### To Reproduce

harvester hoe doesn't work on soul sand

**Comment by OmerBenGera** [comment]
Hey, it seems to work fine for me
Make sure the nether warts are fully grown before trying to use your harvester hoe.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs let me know
