### ISSUE TITLE
HarvesterHoeUseEvent method #getBlocks problem

### ISSUE THREAD

**Issue by Hokib-st** [BG-Software-LLC/WildTools#132]
### Minecraft's Version

1.8.8

### Plugin's Version

2022.7

### Describe the bug

The method #getBlocks do not return all the blocks replaced by the hoe, only return the grass / dirt that was transformed into farmland

### To Reproduce

.

### Additional Information

https://discord.com/channels/554276823010246687/554282655441747998/1050798513862217788

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
