### ISSUE TITLE
Blocks drop that are not meant to drop

### ISSUE THREAD

**Issue by JHarris12345** [BG-Software-LLC/WildTools#133]
### Minecraft's Version

1.19.1

### Plugin's Version

2.13.1

### Describe the bug

If you mine with a trencher tool, blocks drop that are set to have their dropItems cancelled on the BlockBreakEvent. This plugin should fire it's OWN block break event for each block for 2 reasons:

1) The blocks currently cannot be logged by core protect 
2) You cannot check if e.getDropItems is false so items drops when they are not meant to 

### To Reproduce

Mine a block with a trench tool that is not meant to drop items when broken

**Comment by OmerBenGera** [comment]
Add CoreProtect to the "other-plugins" in your config file.
Let me know of it helps.

**Comment by JHarris12345** [comment]
Adding CoreProtect DID allow it to log so that's great thanks. But the main issue here, it does not solve the problem (which leads to a dupe glitch) that if e.getDropItems is set to be false for a broken block, it still will add the drops to your inventory when mined

**Comment by OmerBenGera** [comment]
> Adding CoreProtect DID allow it to log so that's great thanks. But the main issue here, it does not solve the problem (which leads to a dupe glitch) that if e.getDropItems is set to be false for a broken block, it still will add the drops to your inventory when mined

In general, if you want a plugin to be notified about WT's broken blocks, you must add it to the other-plugins or the claiming-plugins lists, as described in the config and the wiki.
However, I dont think I added a check for the getDropItems anyways so I dont believe it will fix the issue.
I will let you know once its patched

**Comment by JHarris12345** [comment]
Ye I added it to that list and nothing. Thanks

**Comment by OmerBenGera** [comment]
@JHarris12345 Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know by replying here
