### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by CayeOficial** [BG-Software-LLC/WildTools#134]
### Minecraft's Version

1.17.1 pufferfish

### Plugin's Version

2022.7 - But confirmed to work on the lastest dev build

### Describe the bug

https://youtu.be/73hZgJR5ka4
You can actually duplicate comparators (yeah, only comparators, idk why) by using a 3x3 pickaxe
A video is worth more than 1000 words

### To Reproduce

Do a 3x1 pillar, put a comparator at the top, break the middle block with a 3x3 pickaxe and then break the comparator with a 3x3 pickaxe, infinite comparators.

### Additional Information

Doesn't work on 1.16.5

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know
