### ISSUE TITLE
Could not pass event PlayerInteractEvent to WildTools

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/WildTools#135]
### Minecraft's Version

1.8.8 and BeerSpigot Premium

### Plugin's Version

v2022.7-b90

### Describe the bug

Unsure exactly the cause of the error I'm getting spammed in my console due to haven't really done any further testing. Here is the error I'm getting spammed with this error in my console https://pastebin.com/8KLfWg8b since I've updated the plugin to the latest dev build.

### To Reproduce

I'm unaware of how to reproduce the error

### Additional Information

I'm getting spammed with this error in my console https://pastebin.com/8KLfWg8b

**Comment by OmerBenGera** [comment]
Send me your entire logs file please

**Comment by DJDan21** [comment]
alright will do here is the log file in question https://pastebin.com/LNWheaLe

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
