### ISSUE TITLE
Wild tools not seeing Iridium Skyblock as a claiming plugin 

### ISSUE THREAD

**Issue by BobTheGamerTwitch** [BG-Software-LLC/WildTools#137]
### Minecraft's Version

1.18

### Plugin's Version

WildTools-2022.7.jar

### Describe the bug

Hello, looking for some help, I have the claiming plugin as IRIDIUMSKYBLOCK but players are still able to sell other peoples chests. I have 'only-inside-claim' set to true but this is not preventing players being able to sell other players chests. Players cannot open the chests while still being able to sell them. This also works for harvester hoes in other peoples land.

### To Reproduce

Players are unable to open the chest or harvest the plants, but with a sell wand or harvester hoe, they are able to.

**Comment by OmerBenGera** [comment]
Add "IridiumSkyblock" to the claimings plugin list in your config plugin. Make sure you add it as it's written in /pl.
Let me know if it works.

**Comment by BobTheGamerTwitch** [comment]
Now works! Thanks a ton!
