### ISSUE TITLE
Modify Config.yml file

### ISSUE THREAD

**Issue by JoeDalton9027** [BG-Software-LLC/WildTools#139]
### Minecraft's Version

Hello, i just want to inform you that the trench_pickaxe configuration is no longer valid.

Ingots are no longer dropper into new minecraft versions.

I advise you to 

```js
whitelisted-drops:
    - COAL
    - RAW_IRON
    - RAW_GOLD
    - RAW_COPPER
    - GOLD_NUGGET
    - REDSTONE
    - DIAMOND
    - EMERALD
    - QUARTZ
    - LAPIS_LAZULI
```

I hope this modification will be usefull.
Greetings

### Plugin's Version

WildTools-2022.7-b92.jar

### Describe the bug

Wrong informations in config.yml file

### To Reproduce

Ingots are no longer dropper into new minecraft versions.
They were replaced by raw material.

**Comment by OmerBenGera** [comment]
Not a bug.
