### ISSUE TITLE
Bug with the Trench Pickaxe the blocks and ores are not drop

### ISSUE THREAD

**Issue by iJuju68** [BG-Software-LLC/WildTools#141]
### Minecraft's Version

PaperSpigot-445 1.8.8

### Plugin's Version

2023.1

### Describe the bug

https://user-images.githubusercontent.com/117361864/227935521-7e9c5a21-e6fa-4f4c-ac0e-3351cd409bfe.mp4

Here is a video of my configuration and the problem. 

### To Reproduce

Used the plugin on version 1.8.8 of paper and take the trench pickaxe.

**Comment by OmerBenGera** [comment]
Upload your config file to pastebin and send a link to it here

**Comment by iJuju68** [comment]
https://pastebin.com/ib7Lq56M
This is my confiuration.

**Comment by OmerBenGera** [comment]
There was indeed an issue with dropping items in 1.8.
However, note that Gold Ore drops GOLD_ORE and not GOLD_INGOT. Same goes for Iron Ore.

Update to latest dev build and fix your whitelisted drops, let me know if it works.

**Comment by iJuju68** [comment]
https://user-images.githubusercontent.com/117361864/229107235-8c5a0e64-4b84-4ba2-9bb0-f4354f163005.mp4

I just tested with the development version but it only works with redstone ores and sometimes it is random. The gold and iron ores it gives me sometimes only 1 or not at all. 
Here is the configuration I used to make this video :
`    whitelisted-drops:
    - 'COAL'
    - 'IRON_ORE'
    - 'GOLD_ORE'
    - 'REDSTONE'
    - 'DYE:4'
    - 'DIAMOND'
    - 'EMERALD'
    - 'QUARTZ'`

**Comment by OmerBenGera** [comment]
Checkout latest dev build, hopefully it works now.

**Comment by iJuju68** [comment]
I just tested the last dev build, but I still have the same problem.

**Comment by OmerBenGera** [comment]
> I just tested the last dev build, but I still have the same problem.

Are you sure you use latest dev build?
It works fine for me.

**Comment by iJuju68** [comment]
yes I put the last version, b99

**Comment by iJuju68** [comment]
Do you want to come and test on my server?

**Comment by OmerBenGera** [comment]
Works fine on my server.
Try default config file, as well as test it on a server with only WildTools installed.

**Comment by iJuju68** [comment]
https://user-images.githubusercontent.com/117361864/229286631-088d5f91-ea49-4279-8a36-69f37a765294.mp4

Yes, that's what I did.

**Comment by OmerBenGera** [comment]
What happens if you place yourself only iron ore and then break it?
Does it work?

**Comment by iJuju68** [comment]
https://user-images.githubusercontent.com/117361864/229287450-56b0a228-d261-4cd1-8fa2-a89350cf1889.mp4

If there is 1 ore it works but if there is more nothing is dorp

**Comment by OmerBenGera** [comment]
You were right, my bad. I had WildStacker installed which interfaced with it.
Check out latest dev build, let me know if it works.

**Comment by iJuju68** [comment]
https://user-images.githubusercontent.com/117361864/229349225-26a9bcb1-b35b-42b1-929f-da64befa6645.mp4


Yes now the ores are drop, but I have a problem with auto-collect and unbrackable, when I mine with the pickaxe that collects the ores automatically I only get the coal but not the other ores. For the unbrackable it's a graphic bug, you can see the durability of the pickaxe decreased, you have to take it from your inventory and put it back so that the line disappears. I send you the config of the pickaxe here : https://pastebin.com/Dsk5f6Rj

**Comment by iJuju68** [comment]
Were you able to look into my problem?

**Comment by OmerBenGera** [comment]
About the iron ore not being dropped, this is because gold pickaxes cannot break iron ore in vanilla minecraft.
About the visual glitch bug, it doesn't happen for me, and it's not really fixable anyways.

I am closing this as everything seems to be working :)
