### ISSUE TITLE
Ores wont drop only Diamonds

### ISSUE THREAD

**Issue by ghost** [BG-Software-LLC/WildTools#142]
### Minecraft's Version

1.19.4
Server jar can't be uploaded it's not allowed and the jar is to big to upload as a zip.

### Plugin's Version

Latest dev build

### Describe the bug

When mining ores none gets picked up just destroyed only diamonds gets picked up

### To Reproduce

Download dev build go into the game place down some blocks give your self the pickaxe and mine.

**Comment by OmerBenGera** [comment]
Try latest dev build, let me know if it works

**Comment by Meepion** [comment]
Hi,

I am already on latest dev build #100 01/04/2023 16:24:20. It's not working.

**Comment by OmerBenGera** [comment]
Please upload your config file to pastebin and send a link to it here.

**Comment by OmerBenGera** [comment]
In 1.19.4, Iron Ore (as well as Gold Ore) drop Iron Raw and not Iron Ore.
Change it to be the correct drops, then let me know if it still occurs.

**Comment by Meepion** [comment]
Ah I see, I tried but it didn't fix the issue:

![image](https://user-images.githubusercontent.com/128911591/230588604-83b5f961-715d-49d3-a626-37505134568b.png)

also the cooldown feature doesn't work either.

**Comment by OmerBenGera** [comment]
It should be `RAW_IRON` and `RAW_GOLD` - check if it works after that.
About the cooldown, looking into it as well.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by Meepion** [comment]
The latest you provided fixed the issue. Sorry for late reply.

**Comment by OmerBenGera** [comment]
Good, glad it fixed the issue :)
