### ISSUE TITLE
Auto-collect harvester hoe

### ISSUE THREAD

**Issue by Benntehboss** [BG-Software-LLC/WildTools#143]
### Minecraft's Version

minecraft 1.8.8
ReliableSpigot version 2.4.4

### Plugin's Version

wildtools 2023.1

### Describe the bug

auto-collect on harveste hoe dosent work, wont give u items to ur inventory, drops 1 cane even if 20 is harvested

### To Reproduce

This is the hoe setup i use  

harvester_hoe:
    tool-mode: HARVESTER
    radius: 2
    auto-collect: true
    type: DIAMOND_HOE
    uses: 50000
    name: ' &6&l* &a&lHarvester Hoe &r&6&l*'

**Comment by OmerBenGera** [comment]
Try it on a server with only WildTools installed, let me know if it still occurs.

**Comment by Benntehboss** [comment]
i allready did, changed back to 2022.7 and there it works great again.

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
Try latest dev build, I fixed a bug with drops that might affect this issue as well.

**Comment by Benntehboss** [comment]
i will test in an hour or so and report back.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Awesome.
If the issue happens again let me know
