### ISSUE TITLE
Glowing Items

### ISSUE THREAD

**Issue by Odsidz** [BG-Software-LLC/WildTools#144]
### Minecraft's Version

1.19.2 Paper

### Plugin's Version

Last dev build: 2023.1 b100

### Describe the bug

No glowing items 

### To Reproduce

in config on give item

### Additional Information

my config items:
  baguette_spawner_3:
    tool-mode: CROWBAR
    type: IRON_PICKAXE
    glow: true
    uses: 3
    name: '&6Spawners &fBaguette &7(Clic-droit)'
    lore:
      - '&7Cliquez sur un spawner pour'
      - '&7récupérer celui-ci.'
      - '&7'
      - '&8 ▪ &7Utilisation(s): &f{}'

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
