### ISSUE TITLE
Builder wand doesnt work in water

### ISSUE THREAD

**Issue by ReformedHooper** [BG-Software-LLC/WildTools#145]
### Minecraft's Version

1.18.2

### Plugin's Version

2023.1-b101

### Describe the bug

When I want to build with a builder's ax in water, nothing builds.. Builder's ax does not work in water

### To Reproduce

I mark points in the water and it doesnt work

### Additional Information

I send the video on the discord server

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
