### ISSUE TITLE
BuildTool on crops

### ISSUE THREAD

**Issue by HiddenSeaMC** [BG-Software-LLC/WildTools#149]
### Minecraft's Version

1.19.3

### Plugin's Version

2023.1

### Describe the bug

So :
1. Take the Tools
2. Go near some crops (SugarCane/Wheat/...)
3. Just use the BuilderTool

You will see that it can replace some Crops but it can't replace block so i assume it's a bug ?

### To Reproduce

Look above

**Comment by OmerBenGera** [comment]
You will not be able to use builder wands against crops, as they are not considered as valid blocks.

**Comment by HiddenSeaMC** [comment]
Need to use the builder tool next to a Crops.
Like : 
C - C- C - C - C -C 
X - C - C- C- C- C

X = stone / c = CROPS
Just place use the builder tool on Stone (X), and it will replace the Crops (C)

Can record if you need
