### ISSUE TITLE
Bug/problem in Crowbar Tool

### ISSUE THREAD

**Issue by tomimza** [BG-Software-LLC/WildTools#154]
### Minecraft's Version

Server version: LightSpigot 1.19.4

### Plugin's Version

Latest dev version. Dev Build #2

### Describe the bug

Hello, I have a complaint, and it is that I have a plugin that manages the spawners, the issue is that when removing a spawner with the crowbartool it removes the name and lore of the spawner and leaves it as a default minecraft spawner so my users do not know what is it. (This only happens when using the crowbartool)

My plugin the spawners is: SpawnerMeta

### To Reproduce

-

### Additional Information

-

**Comment by OmerBenGera** [comment]
SpawnerMeta should add support to WildTools by hooking into the API of the plugin and register a custom DropsProvider.
Contact them to do so :)
