### ISSUE TITLE
Quickshop bug

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/WildTools#155]
### Minecraft's Version

1.19.3

### Plugin's Version

#2

### Describe the bug

Hello,

I've encountered an issue while using the sell wand in conjunction with the plugin found at this link: https://modrinth.com/plugin/quickshop-hikari/version/4.1.0.0.

The problem is that when trying to sell claimed crates using the sell wand, it mistakenly allows the sale of baskets instead. Ideally, it should recognize that the crates are already claimed and refrain from selling them. Instead, it ends up selling the contents of the claimed crates.

Thank you for your attention to this matter.

### To Reproduce

no

**Comment by OmerBenGera** [comment]
What happens if you add "Quickshop" (or whatever the plugin is called in `/pl`) to the `claiming-plugins` list in the config file?
Does it fix the problem?

**Comment by Distolfix** [comment]
not work

**Comment by OmerBenGera** [comment]
Please take a video of the issue.

**Comment by Distolfix** [comment]
https://youtu.be/grH9nBtPRbk 

With the sell wand, you can sell the chests of the QuickShop-Hikari plugin from people who are present on your island. Can you solve this? This is an example

**Comment by Distolfix** [comment]
![image](https://github.com/BG-Software-LLC/WildTools/assets/73421268/32a28173-a54f-461b-9790-b35deda9e572)


not work this

**Comment by OmerBenGera** [comment]
What if you try to access other chests? (ones that you didn't create)

**Comment by Distolfix** [comment]
https://cdn.discordapp.com/attachments/1119193136619585577/1119691601338445925/image.png

**Comment by OmerBenGera** [comment]
What the issue is then?
This looks like an intended behavior for me.

**Comment by Distolfix** [comment]
I don't know, I just know that with the sellchest, the shops that make players are sold

**Comment by OmerBenGera** [comment]
Sell wands will work on any container, unless you don't have access to it.
Because you do, then it is technically an intended behavior.

You could make a custom plugin that prevents sell wands from working on quickshop chests.
