### ISSUE TITLE
wildtools and shopgui

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildTools#157]
### Minecraft's Version

1.20.1 paper last version

### Plugin's Version

last version

### Describe the bug

when i sell with the wand i should get the normal store permission not the vip one in shopgui

could there be some way for it to detect if I have permission in the VIP store or not, so I don't need to keep using multiply in the settings

if I am not mistaken the SuperHoppers plugin does this, it checks if I have permission in the vip store or not

### To Reproduce

check if I have permission in the vip store if I don't then I will sell for the /shop price

if I am vip then I will sell it for the /shopvip price

**Comment by SrMonsterYT** [comment]
ShopGuiPlugin shopGuiPlugin = ShopGuiPlusApi.getPlugin();
            ItemStack i = simpleItem.getItem();
            i.setAmount(1);
            ShopItem shopItem;
            if (player != null && player.isOnline()) {
                shopItem = shopGuiPlugin.getShopManager().findShopItemByItemStack(player.getPlayer(), i, true);
            } else {
                shopItem = shopGuiPlugin.getShopManager().findShopItemByItemStack(i, true);
            }

            if (shopItem != null) {
                double price = player != null && player.isOnline() ?
                        shopItem.getSellPriceForAmount(player.getPlayer(), (int) amount) :
                        shopItem.getSellPriceForAmount((int) amount);
                return BigDecimal.valueOf(price);
            } else {
                worth = itemWorth.getOrDefault(s, BigDecimal.ZERO);
            }
            
            this makes wiltools respect shopgui's vip and non-vip stores

**Comment by OmerBenGera** [comment]
The issue is that WildTools caches the prices and probably conflicts between players.
I will look into that.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is better.

**Comment by SrMonsterYT** [comment]
is solved, thank you very much

**Comment by SrMonsterYT** [comment]
we still have a problem here some items from lojavip the wand is selling the value of the normal store, for example diamond is 80$ in the normal store and in lojavip 90$, when I go to sell it sells for 90$, now when it is blaze stick, it sells for 15$ more the value would be 20$, it also happens with slime balls the value in the normal store is 300$ and in lojavip is 400$ it is selling for 300$, 50% of the things in the vip store are still not being detected

**Comment by OmerBenGera** [comment]
The plugin checks for the first price it finds, not the highest one for better performance.
You can request it as a feature request.
