### ISSUE TITLE
willdtools and Shopgui+ Bug

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildTools#158]
### Minecraft's Version

 Pufferfish version git-Pufferfish-14 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Plugin's Version

last version

### Describe the bug

video youtube https://youtu.be/ceoLZaBh9e4

I can't sell arrows but I can sell them using the /shop command, it seems to be a wildtools bug, everything was normal in 1.19.2, this happened after I upgraded to 1.20.1

### To Reproduce

try to sell arrows

**Comment by OmerBenGera** [comment]
Try it on a server with only WildTools and SGP installed.

**Comment by SrMonsterYT** [comment]
> Try it on a server with only WildTools and SGP installed.

same thing: https://youtu.be/QK3V_EYBa78

**Comment by OmerBenGera** [comment]
> > Try it on a server with only WildTools and SGP installed.
> 
> same thing: https://youtu.be/QK3V_EYBa78

This is obviously not a server with only WildTools and SGP installed.

**Comment by SrMonsterYT** [comment]
> > > Try it on a server with only WildTools and SGP installed.
> > 
> > 
> > same thing: https://youtu.be/QK3V_EYBa78
> 
> This is obviously not a server with only WildTools and SGP installed.

how will shopgui work without an economy plugin?
there is no such thing

**Comment by OmerBenGera** [comment]
> > > > Try it on a server with only WildTools and SGP installed.
> > > 
> > > 
> > > same thing: https://youtu.be/QK3V_EYBa78
> > 
> > 
> > This is obviously not a server with only WildTools and SGP installed.
> 
> how will shopgui work without an economy plugin? there is no such thing
> 
> https://prnt.sc/N7CYkI1ppdO1

Then install an economy plugin as well.
Install the least required plugins as possible to run the two plugins.

**Comment by SrMonsterYT** [comment]
> 



> > > > Try it on a server with only WildTools and SGP installed.
> > > 
> > > 
> > > same thing: https://youtu.be/QK3V_EYBa78
> > 
> > 
> > This is obviously not a server with only WildTools and SGP installed.
> 
> how will shopgui work without an economy plugin? there is no such thing
> 
> https://prnt.sc/N7CYkI1ppdO1

I already did that here is

**Comment by SrMonsterYT** [comment]
any news about the bug?

**Comment by OmerBenGera** [comment]
> > 
> 
> > > > > Try it on a server with only WildTools and SGP installed.
> > > > 
> > > > 
> > > > same thing: https://youtu.be/QK3V_EYBa78
> > > 
> > > 
> > > This is obviously not a server with only WildTools and SGP installed.
> > 
> > 
> > how will shopgui work without an economy plugin? there is no such thing
> > https://prnt.sc/N7CYkI1ppdO1
> 
> I already did that here is

Okay, and what are the results?
Take a video of the issue with only the minimum required plugins installed.

**Comment by SrMonsterYT** [comment]
> > > 
> > 
> > 
> > > > > > Try it on a server with only WildTools and SGP installed.
> > > > > 
> > > > > 
> > > > > same thing: https://youtu.be/QK3V_EYBa78
> > > > 
> > > > 
> > > > This is obviously not a server with only WildTools and SGP installed.
> > > 
> > > 
> > > how will shopgui work without an economy plugin? there is no such thing
> > > https://prnt.sc/N7CYkI1ppdO1
> > 
> > 
> > I already did that here is
> 
> Okay, and what are the results? Take a video of the issue with only the minimum required plugins installed.

i already made it the video in the end i show the plugins are only the economy plugins and the wiltools and wildchest
 
https://youtu.be/QK3V_EYBa78

**Comment by OmerBenGera** [comment]
Get rid of WildChests... This is not an essential plugin for running WildTools.
Test it on a regular chest, no WildChests installed, check if it still occurs.

**Comment by SrMonsterYT** [comment]
> 


same thing  https://youtu.be/posxWh286TI

**Comment by OmerBenGera** [comment]
Upload logs file of that session to pastebin and send a link to it here.

**Comment by OmerBenGera** [comment]
latest.log file

**Comment by SrMonsterYT** [comment]
it seems that the problem was in the shopgui API has already been solved by them, thanks

**Comment by SrMonsterYT** [comment]
this bug still continues

**Comment by OmerBenGera** [comment]
I am using SGP's API to get sell prices of items.
If it doesn't work, you should contact them for support.
The code that gets prices for items can be found here: https://github.com/BG-Software-LLC/ShopsBridge/blob/master/Hooks/ShopGUIPlus1_80/src/main/java/com/bgsoftware/common/shopsbridge/ShopsBridge_ShopGUIPlus1_80.java
