### ISSUE TITLE
Trench Pickaxe / Sell Stick huge bug

### ISSUE THREAD

**Issue by DiktatorAladeen** [BG-Software-LLC/WildTools#159]
### Minecraft's Version

1.19.4

### Plugin's Version

The latest

### Describe the bug

Players can use trench pickaxe on other chests protected by LWC plugin? Can you do something about that?

Also players can sell items with sell stick in other regions protected by Protection stones ( World Guard )

### To Reproduce

/

### Additional Information

/

**Comment by OmerBenGera** [comment]
Add "LWC" (or however the plugin is called in /pl) to the claiming-plugins list in your config file.

In general, any plugin that somehow restricts breaking of blocks can be added to this list and they will be supported.
