### ISSUE TITLE
Lightning Wand Uses won't go down

### ISSUE THREAD

**Issue by Redwolf223** [BG-Software-LLC/WildTools#160]
### Minecraft's Version

1.8.8, PandaSpigot

### Plugin's Version

2023.2 

### Describe the bug

The Lightning Wand uses won't go down even if set to 1 or 200. You can use it how many times you want.

### To Reproduce

Give yourself the lightning wand and use it.

**Comment by Redwolf223** [comment]
Yes, i was in survival mode

**Comment by Redwolf223** [comment]
Yes

https://github.com/BG-Software-LLC/WildTools/assets/58572866/a6d55126-79b0-4680-9845-3f5f7a4013a6

**Comment by OmerBenGera** [comment]
I can't replicate the issue myself.
Use default files, check if it still occurs.

**Comment by Redwolf223** [comment]
I've tried with default files newly generated.
 
Paper 1.8.9, b10 devbuild. Same problem

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
