### ISSUE TITLE
DUPE Bug

### ISSUE THREAD

**Issue by BufalinoSD** [BG-Software-LLC/WildTools#162]
### Minecraft's Version

1.19.4

### Plugin's Version

ALL

### Describe the bug

You can duplicate any block that depends on the one that is broken with the TRENCH PICKAXES

### To Reproduce

Follow steps of the video 
https://youtu.be/UH3ij9F0ZII

**Comment by OmerBenGera** [comment]
Send me your configuration file of WildTools, as I can't seem to replicate the issue straight away.

**Comment by BufalinoSD** [comment]
https://paste.md-5.net/alisofijaz.shell

**Comment by BufalinoSD** [comment]
Remember that there is a direction that the dupe does not work, I indicate it with the f3 in the video.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
