### ISSUE TITLE
Trench Pickaxe Bugs

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [BG-Software-LLC/WildTools#166]
### Minecraft's Version

![image](https://github.com/BG-Software-LLC/WildTools/assets/70504198/aa9dac8c-29c3-4dd5-a0c9-af58571bb847)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/WildTools/assets/70504198/16479cb4-dd72-4cf1-8f65-60c4d92237d8)

### Describe the bug

1. Pickaxe does not drop items in chests

2. Pickaxe does not break water or lava

### To Reproduce

1. Make a chest with items in it, then break a block around it with the trench pickaxe

2. Try breaking water or lava with the trench pickaxe

### Additional Information

While the second one may be intentional, it would be nice to have some way around it.

**Comment by MinecraftMan1013number2** [comment]
Any update on this?

**Comment by OmerBenGera** [comment]
Regarding water/lava - this is intended, you can't remove water & lava in vanilla using tools.
Regarding items from chests not dropped, it works fine for me. Make sure you're not in creative mode.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
