### ISSUE TITLE
Sell Wands with Iridiumskyblock

### ISSUE THREAD

**Issue by UhhBlaze** [BG-Software-LLC/WildTools#167]
### Minecraft's Version

1.20.1

### Plugin's Version

2023.2

### Describe the bug

While using both iridiumskyblock and wildtools, Sell Wands are able to be used on any chest, even on islands that are not owned by player. 

For example, I can get a Sell Wand and go to another persons island and use my sell wand to sell the items in chests.

### To Reproduce

Download both iridiumskyblock and wildtools - attempt to sell items from chest on someone elses island

### Additional Information

If iridiumskyblock islands cannot be supported, my apologies! thank you

**Comment by OmerBenGera** [comment]
Add "IridiumSkyblock" to the claiming-plugins list in the config file of WildTools.
Any plugin that you want to be supported should be added there.
