### ISSUE TITLE
Could not pass event PlayerInteractEvent to WildTools v2023.2-b12

### ISSUE THREAD

**Issue by Ken-Shinigami** [BG-Software-LLC/WildTools#168]
### Minecraft's Version

1.20.1 Paper, Purpur

### Plugin's Version

WildTools v2023.2-b12 dev build and also v2023.2 stable from Spigot

### Describe the bug

As soon as plugin is started it gives the following error:

> [Tue 16:26:07 ERROR Minecraft] Could not pass event PlayerInteractEvent to WildTools v2023.2-b12
--
  | java.lang.NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because "com.bgsoftware.wildtools.tools.WTool.toolBlockBreak" is null
  | at WildTools-2023.2-b12.jar//com.bgsoftware.wildtools.listeners.BlocksListener.onBlockInteract(BlocksListener.java:91)
  | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1440.execute(Unknown Source)
  | at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
  | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
  | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
  | at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
  | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
  | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
  | at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:591)
  | at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:548)
  | at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:542)
  | at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:199)
  | at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:2010)
  | at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42)
  | at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15)
  | at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51)
  | at net.minecraft.server.TickTask.run(TickTask.java:18)
  | at net.minecraft.util.thread.BlockableEventLoop.doRunTask

### To Reproduce

Problem starts immediately after being loaded / server starting and continuously spams the console.

### Additional Information

I have looked at the config file and tried adding our economy plugin instead of ShopGUI (we're using a different plugin) and that made no difference. I also added our claiming plugin and that also made no difference.

**Comment by OmerBenGera** [comment]
This error may happen if you don't have any tools available.
Is this the case on your server?

**Comment by Ken-Shinigami** [comment]
> This error may happen if you don't have any tools available. Is this the case on your server?

We have trench picks, sell wands and lightning wands on the server.

**Comment by OmerBenGera** [comment]
Weird.
Anyways, this should be fixed on latest version of WildTools.
Let me know if it still occurs

**Comment by Ken-Shinigami** [comment]
It's working perfectly. Thank you!
