### ISSUE TITLE
Harvester hoe + AureliumSkills 

### ISSUE THREAD

**Issue by Shinigammi** [BG-Software-LLC/WildTools#169]
### Minecraft's Version

1.20.1

### Plugin's Version

Latest Dev

### Describe the bug

i have a problem with harvester hoe, when i farm with harvester hoe i don't get xp from AureliumSkills , but i get from trench pickaxe why?

### To Reproduce

get xp from harvster hoe

### Additional Information

no

**Comment by OmerBenGera** [comment]
What skill type do we talk about?

**Comment by Shinigammi** [comment]
Farming Skill

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
