### ISSUE TITLE
Uses doesn't go down for tools

### ISSUE THREAD

**Issue by JHarris12345** [BG-Software-LLC/WildTools#171]
### Minecraft's Version

Paperspigot 1.20.1

### Plugin's Version

2023.2

### Describe the bug

When you use a wand with uses it doesnt go down

### To Reproduce

Here is my wand. If you use it, it doesn't go down

  500_condense:
    tool-mode: CRAFTING
    type: CARROT_ON_A_STICK
    unbreakable: true
    uses: 500
    name: '&f --{ &9&lCondensing Wand &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Hit a chest to condense all minerals inside!'
    - '&f'
    - '&9&l Uses:'
    - '&f   {}'
    - '&f'
    - '&8&m---------------------------------------'
    craftings:
    - IRON_BLOCK
    - EMERALD_BLOCK
    - BONE_BLOCK
    - DIAMOND_BLOCK
    - REDSTONE_BLOCK
    - LAPIS_BLOCK
    - NETHERITE_BLOCK
    - SLIME_BLOCK
    - GOLD_BLOCK
    - COAL_BLOCK
    - MELON
    - COPPER_BLOCK
    - RAW_COPPER_BLOCK
    - RAW_IRON_BLOCK
    - RAW_GOLD_BLOCK

**Comment by OmerBenGera** [comment]
Make sure you are not in crative mode

**Comment by OmerBenGera** [comment]
Does ir happen with latest version?

**Comment by JHarris12345** [comment]
Yup

**Comment by OmerBenGera** [comment]
I am closing this as it doesn't seem to be a bug
If the issue continues, let me know
