### ISSUE TITLE
The uses in HARVESTER mode do not decrease

### ISSUE THREAD

**Issue by BufalinoSD** [BG-Software-LLC/WildTools#172]
### Minecraft's Version

Pufferfish version git-Pufferfish-27 (MC: 1.20.1)

### Plugin's Version

WildTools-2023.3-b21

### Describe the bug

The uses of the hoe in HARVESTER mode do not decrease.

### To Reproduce

https://youtu.be/1L70Ic2kT2c

### Additional Information

My configuration https://paste.md-5.net/mobamogavu.shell

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If it still occurs, let me know
