### ISSUE TITLE
Possible bug in the tool mode.

### ISSUE THREAD

**Issue by BufalinoSD** [BG-Software-LLC/WildTools#173]
### Minecraft's Version

Pufferfish version git-Pufferfish-27 (MC: 1.20.1)

### Plugin's Version

WildTools-2023.3-b21

### Describe the bug

I couldn't reproduce it, but several of my users sent me videos showing that blocks don't finish breaking when they use the tool with tool mode.

### To Reproduce

https://www.youtube.com/watch?v=TtambSupl14
https://www.youtube.com/watch?v=N9oav7vAkY8

### Additional Information

I'm leaving my configuration in case it contributes in any way. 
https://paste.md-5.net/yagutimeda.coffeescript

**Comment by OmerBenGera** [comment]
I can't seem to replicate it neither.
Let me know how to replicate it, otherwise I won't be able to fix it.
