### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildTools#174]
### Minecraft's Version

Pufferfish version git-Pufferfish-27

### Plugin's Version

WildTools v2023.3-b21

### Describe the bug

https://mclo.gs/V2a0Fek

### To Reproduce

this keeps happening on the console I still haven't found out why

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by SrMonsterYT** [comment]
> Check out latest dev build, let me know if it works

the error no longer appears, I believe it has been resolved thank you
