### ISSUE TITLE
Harvester Hoe Autosell 

### ISSUE THREAD

**Issue by Shinigammi** [BG-Software-LLC/WildTools#175]
### Minecraft's Version

latest. purpur 1.20.1

### Plugin's Version

Latest Stable 

### Describe the bug

Harvester Hoe Autosell sometimes don't work with aurelium skills,  ( we tested it on a melon, it just sometimes doesn't come in the inventory, it just falls from the side as if we were farming it down without a hoe

### To Reproduce

Fix

**Comment by OmerBenGera** [comment]
Make sure you add that plugin to the `other-plugins` list in the config file.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
