### ISSUE TITLE
Deepslate not dropping with trench

### ISSUE THREAD

**Issue by Elijahzeal** [BG-Software-LLC/WildTools#177]
### Minecraft's Version

Pufferfish 17 (1.20.1)

### Plugin's Version

Wildtools 2023.3

### Describe the bug

When using a trench pickaxe and breaking deepslate, deepslate isn't dropped. ID is added to the whitelisted blocks yet the block still doesn't drop.

### To Reproduce

Get a Netherite Pickaxe.
Add Trench to the pickaxe.
Add 3 to the break-level.
Mine deepslate.
No deepslate drops.

### Additional Information

Tried with the default diamond trench pickaxe and deepslate doesn't drop.

**Comment by OmerBenGera** [comment]
Upload your config file to pastebin and send a link to it here.
In general, these type of issues are mostly related to faulty configuration, so make sure you have the deepslate drops whitelisted correctly.

**Comment by Elijahzeal** [comment]
https://pastebin.com/FbDEHEHd

**Comment by OmerBenGera** [comment]
Deepslate drops Cobbled Deepslate unless you have silk touch on your pickaxe.
Add `COBBLED_DEEPSLATE` and the issue will be fixed.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be solved
If the issue continues let me know
