### ISSUE TITLE
Compatibility issue with factions uuid

### ISSUE THREAD

**Issue by PingSpoof** [BG-Software-LLC/WildTools#179]
### Minecraft's Version

1.20.2 paper

### Plugin's Version

Last 2023.3 b24

### Describe the bug

If you use the tools on your factions claim with the last version of fac uuid, it will spam error in console and don't work in game.

[20:20:37 ERROR]: Could not pass event PlayerInteractEvent to WildTools v2023.3-b24
java.lang.NoSuchMethodError: 'boolean com.massivecraft.factions.listeners.FactionsBlockListener.playerCanBuildDestroyBlock(org.bukkit.entity.Player, org.bukkit.Location, java.lang.String, boolean)'
        at com.bgsoftware.wildtools.hooks.ClaimsProvider_FactionsUUID02.isPlayerClaim(ClaimsProvider_FactionsUUID02.java:17) ~[WildTools-2023.3-b24.jar:?]
        at com.bgsoftware.wildtools.handlers.ProvidersHandler.lambda$isInsideClaim$0(ProvidersHandler.java:180) ~[WildTools-2023.3-b24.jar:?]

### To Reproduce

Just use the last dev build with factions uuid and then use the tray pickaxe or an another tool inside your claim and the plugin will spam an error in console every time you break a block.

**Comment by OmerBenGera** [comment]
I am using latest version of WildTools (b24) and FactionsUUID (b329) and it works just fine.
Please send me a link to the FactionsUUID you use and the exact version you use.

**Comment by PingSpoof** [comment]
FactionsUUID b333

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
Let me know if it works

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue continues let me know
