### ISSUE TITLE
Trench pickaxes

### ISSUE THREAD

**Issue by DiktatorAladeen** [BG-Software-LLC/WildTools#180]
### Minecraft's Version

1.20.2 paper

### Plugin's Version

2023-3-b24

### Describe the bug

Hi, Trench pickaxe sometimes are working, sometimes not!

### To Reproduce

I try /tools reload and this error is showing

### Additional Information

https://pastebin.com/pz68jqpC

**Comment by OmerBenGera** [comment]
The reload command failed as it couldn't find the `config.yml` resource file in the jar of the plugin.
A restart should fix the issue.
