### ISSUE TITLE
Wildtools + EcononomyShopGui Premium - Don't Work

### ISSUE THREAD

**Issue by mk9395** [BG-Software-LLC/WildTools#182]
### Minecraft's Version

1.20.2+

### Plugin's Version

WildTools-2023.3-b25

### Describe the bug

I'm having trouble syncing with EconomyShopGui Premium!
Even though there are items in the store, when you put the items in the chest and use SellWand, the system says the item cannot be found for sale.

### To Reproduce

Currently plugins do not work with EconomyShopGui Premium

### Additional Information

This is my config file information: https://mclo.gs/6VLxsAs

**Comment by OmerBenGera** [comment]
I'll need a copy of EconomyShopGUI Premium so I can add support for it (the free version works fine).
What is your discord? I'll open a ticket for you on there so you can send me a copy of the plugin.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
