### ISSUE TITLE
Wildtools - Harvester hoe

### ISSUE THREAD

**Issue by DiktatorAladeen** [BG-Software-LLC/WildTools#183]
### Minecraft's Version

![image](https://github.com/BG-Software-LLC/WildTools/assets/34982264/3d0b8ed7-2080-4b6a-a7dd-a9c6996abf55)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/WildTools/assets/34982264/96c4f222-4ecf-4b5c-a733-7f60d62ca32e)

### Describe the bug

Harvester hoe is not dropping crops on floor, its only replanting
This error is in console: https://pastebin.com/0cGqEytT

### To Reproduce

test

### Additional Information

https://pastebin.com/0cGqEytT

**Comment by OmerBenGera** [comment]
Please upload the entire session logs to pastebin and send a link to it here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs let me know
