### ISSUE TITLE
sell-mode harvest hoe lag

### ISSUE THREAD

**Issue by shika258** [BG-Software-LLC/WildTools#184]
### Minecraft's Version

Paper 1.20.4

### Plugin's Version

2023.3

### Describe the bug

Activating sell-mode with harvest hoe causes chat spam and a large loss of TPS.

### To Reproduce

Activating sell-mode with harvest hoe causes chat spam and a large loss of TPS.

**Comment by OmerBenGera** [comment]
Take a spark profiler and send it here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
