### ISSUE TITLE
Magnet picks up items in other players islands

### ISSUE THREAD

**Issue by RVSkeLe** [BG-Software-LLC/WildTools#186]
### Minecraft's Version

Purpur 1.16.5

### Plugin's Version

2023.3

### Describe the bug

When you go in another player island (using SuperiorSkyblock2) with the Magnet Wand you can pick up items even if the settings is disabled in /is settings.

### To Reproduce

Go to another player island, let them drop something, right click with magnet wand, that's it.

**Comment by OmerBenGera** [comment]
Try adding SuperiorSkyblock to the claiming plugins list. Does it help?

**Comment by OmerBenGera** [comment]
> I've thought about that but I couldn't find it in the Wiki, do I just add SuperiorSkyBlock?

It should be identical to the name in /pl, so it would be `SuperiorSkyblock2`

**Comment by RVSkeLe** [comment]
events-manipulations:
  # A list of all the plugins that handle claims here on your server.
  # If one of the plugins here cancel the events, then WT will know that the player doesn't have access.
  claiming-plugins:
  - SuperiorSkyblock2
And I did the /tools reload command but it doesn't fix the issue, do I need a full server restart?

**Comment by RVSkeLe** [comment]
Even after a full server restart the problem is still there @OmerBenGera

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if is fixed

**Comment by RVSkeLe** [comment]
> Check out latest dev build, let me know if is fixed

Seems fixed.
Thank you for the excellent support you are providing, even for the other issues
