### ISSUE TITLE
Cannot use recipes.yml file

### ISSUE THREAD

**Issue by iJuju68** [BG-Software-LLC/WildTools#191]
### Minecraft's Version

Paper 1.8.8

### Plugin's Version

2023.3

### Describe the bug

When I want to create a custom craft it doesn't work, I get no error in the console when starting or reloading the plugin.
My config : 
tools:
  Pioche_3x3:
    tool-mode: CUBOID
    break-level: 3
    only-same-type: false
    unbreakable: false
    type: DIAMOND_PICKAXE
    name: '&6&lPioche 3x3 '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Cette pioche casse une zone de &e&l3x3'
    - '&f'
    - '&7 Seuls les minerais droppents.'
    - '&8&m---------------------------------------'
    enchants:
    - DIG_SPEED:5
    - DURABILITY:5
    blacklisted-blocks:
    - MOB_SPAWNER
    - LAPIS_ORE
    whitelisted-drops:
    - COAL
    - IRON_ORE
    - GOLD_ORE
    - REDSTONE
    - DYE:4
    - DIAMOND
    - EMERALD
    - QUARTZ
  Pioche_3x3_Fortune:
    tool-mode: CUBOID
    break-level: 3
    only-same-type: false
    unbreakable: false
    type: DIAMOND_PICKAXE
    name: '&6&lPioche 3x3 de fortune'
    lore:
    - '&8&m---------------------------------------'
    - '&7 Cette pioche casse une zone de &e&l3x3'
    - '&f'
    - '&7 Seuls les minerais droppents.'
    - '&8&m---------------------------------------'
    enchants:
    - DIG_SPEED:5
    - DURABILITY:5
    - LOOT_BONUS_BLOCKS:1
    blacklisted-blocks:
    - MOB_SPAWNER
    - LAPIS_ORE
    whitelisted-drops:
    - COAL
    - IRON_ORE
    - GOLD_ORE
    - REDSTONE
    - DYE:4
    - DIAMOND
    - EMERALD
    - QUARTZ
  Bâton_de_vente:
    tool-mode: SELL
    cooldown: 5000
    uses: 1000
    multiplier: 1.0     
    type: RECORD_8
    name: '&6&lBâton de vente'
    lore:
    - '&8&m---------------------------------------'
    - '&7 Ce bâton vend tout les objets qui se trouvent'
    - '&7 dans un coffre (voir /shop).'
    - '&7'
    - '&6&lMultiplicateur:'
    - '&f   x1.0'
    - '&e&l Utilisations restantes:'
    - '&f   {}'
    - '&f'
    - '&8&m---------------------------------------'
  Harvester2:
    tool-mode: HARVESTER
    radius: 2
    auto-collect: true
    type: WOOD_HOE
    uses: 1000
    name: '&6&lHarvester &e&l2x2'
    lore:
    - '&8&m---------------------------------------'
    - '&7 Clique sur une plantation pour récolter et'
    - '&7 replanté automatiquement. Les récoltes '
    - '&7 sont mis dans ton inventaire.'
    - '&e Rayon : &6&l2x2'
    - '&e&l Utilisations restantes:'
    - '&f   {}'
    - '&8&m---------------------------------------'
  Harvester3:
    tool-mode: HARVESTER
    radius: 3
    auto-collect: true
    type: WOOD_HOE
    uses: 1000
    name: '&6&lHarvester &e&l3x3'
    lore:
    - '&8&m---------------------------------------'
    - '&7 Clique sur une plantation pour récolter et'
    - '&7 replanté automatiquement. Les récoltes '
    - '&7 sont mis dans ton inventaire.'
    - '&e Rayon : &6&l3x3'
    - '&e&l Utilisations restantes:'
    - '&f   {}'
    - '&8&m---------------------------------------'    
  Harvester4:
    tool-mode: HARVESTER
    radius: 4
    auto-collect: true
    type: WOOD_HOE
    uses: 1000
    name: '&6&lHarvester &e&l4x4'
    lore:
    - '&8&m---------------------------------------'
    - '&7 Clique sur une plantation pour récolter et'
    - '&7 replanté automatiquement. Les récoltes '
    - '&7 sont mis dans ton inventaire.'
    - '&e Rayon : &6&l4x4'
    - '&e&l Utilisations restantes:'
    - '&f   {}'
    - '&8&m---------------------------------------'   
  Main_de_Sable:
    tool-mode: BUILDER
    type: GOLD_AXE
    whitelisted-blocks:
    - SAND    
    uses: 150
    length: 10
    name: '&e&lMain de Sable'
    lore:
    - '&8&m---------------------------------------'
    - '&7 Clique droit pour créer un pilier de 10 blocs'
    - '&7 dans la direction souhaité.'
    - '&7 Fonctionne uniquement avec les blocs de sables.'
    - '&e&l Utilisations restantes:'
    - '&f   {}'
    - '&8&m---------------------------------------'
  Main_d_obsidienne:
    tool-mode: BUILDER
    type: GOLD_SPADE
    whitelisted-blocks:
    - OBSIDIAN    
    uses: 150
    length: 10
    name: '&5&lMain d''obsidienne'
    lore:
    - '&8&m---------------------------------------'
    - '&7 Clique droit pour créer un pilier de 10 blocs'
    - '&7 dans la direction souhaité.'
    - '&7 Fonctionne uniquement avec les blocs d''obsidienne.'
    - '&e&l Utilisations restantes:'
    - '&f   {}'
    - '&8&m---------------------------------------' 
  Main_de_Pierres:
    tool-mode: BUILDER
    type: GOLD_HOE
    whitelisted-blocks:
    - COBBLESTONE    
    uses: 150
    length: 10
    name: '&7&lMain de Pierre'
    lore:
    - '&8&m---------------------------------------'
    - '&7 Clique droit pour créer un pilier de 10 blocs'
    - '&7 dans la direction souhaité.'
    - '&7 Fonctionne uniquement avec les blocs de pierre.'
    - '&e&l Utilisations restantes:'
    - '&f   {}'
    - '&8&m---------------------------------------'       
  Pelle_ultime:
    tool-mode: CUBOID
    break-level: 2
    only-same-type: false
    unbreakable: true
    type: DIAMOND_SPADE
    name: '&5&lPelle Ultime '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Cette pelle casse une zone de &e&l2x2'
    - '&7 Cette pelle n''a pas de durabilité'
    - '&f'
    - '&7 Tout les blocs droppent.'
    - '&8&m---------------------------------------'
    enchants:
    - DIG_SPEED:5
    blacklisted-blocks:
    - MOB_SPAWNER
    whitelisted-drops:
    - DIRT
    - GRASS
    - SOUL_SAND
    - SAND
    - GRAVEL
    
    Recipes config :
    recipes:
  Pioche_3x3:
  - 'AIR, DIAMOND, AIR'
  - 'AIR, STICK, AIR'
  - 'AIR, AIR, AIR'

### To Reproduce

Use this config

**Comment by OmerBenGera** [comment]
I have the following in my recipes file. I restarted it and it works fine:
```
recipes:
  trench_pickaxe:
  - 'AIR, DIAMOND, AIR'
  - 'AIR, STICK, AIR'
  - 'AIR, AIR, AIR'
```

**Comment by iJuju68** [comment]
With the dev version it works.
But when I start the plugin I get this error:
[16:36:09 WARN]: [WildTools] Task #27 for WildTools v2023.3-b33 generated an exception
java.lang.NoClassDefFoundError: com/massivecraft/factions/perms/PermissibleAction

**Comment by OmerBenGera** [comment]
> With the dev version it works. But when I start the plugin I get this error: [16:36:09 WARN]: [WildTools] Task #27 for WildTools v2023.3-b33 generated an exception java.lang.NoClassDefFoundError: com/massivecraft/factions/perms/PermissibleAction

Are you using MassiveCraft Factions?

**Comment by iJuju68** [comment]
I use SaberFactions

**Comment by OmerBenGera** [comment]
> SaberFactions

Fixed in latest dev build
Closing this for now :)
