### ISSUE TITLE
CONSOLE ERROR

### ISSUE THREAD

**Issue by Aides123** [BG-Software-LLC/WildTools#194]
### Minecraft's Version

pufferfish 1.20.4

### Plugin's Version

#39

### Describe the bug

https://pastebin.com/QbjQN54h
#193 

### To Reproduce

Just use wand builder until you get an error in the console

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs, let me know
