### ISSUE TITLE
Axe

### ISSUE THREAD

**Issue by Bimmalord** [BG-Software-LLC/WildTools#197]
### Minecraft's Version

Java Minecraft version 1.20.2

### Plugin's Version

WildTools-2024.1-b41 (dev build)
WildTools-2023.3 (stable build)

### Describe the bug

I made a power axe with Pillar mode and it can't cut the nether trees in the nether in the overworld it still works.

### To Reproduce

I made a power axe with Pillar mode and it can't cut the nether trees in the nether in the overworld it still works.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
