### ISSUE TITLE
Instant break doesnt work on reinforced deepslate

### ISSUE THREAD

**Issue by JHarris12345** [BG-Software-LLC/WildTools#200]
### Minecraft's Version

1.20.4

### Plugin's Version

2024.1-b41

### Describe the bug

A trencher picker that has Instant break set to true will NOT instant break reinforced deeplsate

### To Reproduce

Mine reinforced deepslate with an instant break tool

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed
