### ISSUE TITLE
Condensing wand not giving the right amount of items

### ISSUE THREAD

**Issue by JHarris12345** [BG-Software-LLC/WildTools#208]
### Minecraft's Version

1.21

### Plugin's Version

2024.3-b51

### Describe the bug

Condensing Wands (and I think any other wands that handle adding items to an inventory as 1.21 changed this mechanic) don't give the right items when the result is an item stack of over 64. Below is a video example:

1) I have 18 stacks of gold ingots (1152 gold ingot)
2) I condense it which should give me 128 blocks of gold
3) It SAYS in chat that it condensed 128 items, so that's c

https://github.com/user-attachments/assets/92dce6f6-e037-4493-8440-ab5fc730f2a1

orrect. But as you can see, it gave me 93 blocks

In 1.21 item stacks can get to 99 so you should set the max inventory stack size to 64 prior to giving the items. That's a potential fix

### To Reproduce

Steps above

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
