### ISSUE TITLE
MAJOR WildTools issue

### ISSUE THREAD

**Issue by JHarris12345** [BG-Software-LLC/WildTools#210]
### Minecraft's Version

1.21.1

### Plugin's Version

2024.3-b52

### Describe the bug

The plugin can accidentally register enchants more than once and prevent players from joining until a restart. Here is a client log:

https://pastes.dev/qJEQk4Etil

It should be made so if the enchant is already registered, it doesn't register it again. The ViaVersion dev said this:

"Uhh not sure, Paper has proper API to register them once but it doesn't look like it's using API"

### To Reproduce

Not 100% sure

**Comment by JHarris12345** [comment]
I will say, this only prevents 1.21.2 and 1.21.3 clients from joining when this error occurs. If you want a definitive and easy way to replicate it, simply /plugman reload the plugin :)

**Comment by JHarris12345** [comment]
Also since I dont use the glowing enchant, can you make it configurable if it even tries to register at ALL. Because I will disable this entirely so it doesnt cause me issues

**Comment by OmerBenGera** [comment]
Reloads of the plugin are not supported.
If you dont reload it, does it still happen?

**Comment by JHarris12345** [comment]
If you could just make a config option to register the enchantment that would be amazing thank you!

**Comment by OmerBenGera** [comment]
It is fixed in latest dev build.
I still do not recommend reloading the plugin, it is an unsupported behavior.

**Comment by JHarris12345** [comment]
Thanks!
