### ISSUE TITLE
Sell Wand Support for Boosters plugin

### ISSUE THREAD

**Issue by kamber5** [BG-Software-LLC/WildTools#211]
### Minecraft's Version

Paper version 1.21.1-119-master@7cd4f2c

### Plugin's Version

2024.3-b52

### Describe the bug

When players start the Sell Multiplier for 2x and use their sell wand it uses the original prices from ShopGUI+ plugin and not the 2x boosted ones.

Here is the booster plugin link:
https://www.spigotmc.org/resources/boosters-%E2%AD%95-eula-friendly-global-buffs-%E2%9C%85-jobs-skills-sell-multipliers-%E2%9C%A8-create-your-own.99928/

### To Reproduce

- Start Sell Booster
- Take Sell Wand
- Sell something from ShopGUI+
- /sell hand sells 2x, sell wand sells for original price

**Comment by OmerBenGera** [comment]
#209
