### ISSUE TITLE
Wild Tools console issue

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/WildTools#214]
### Minecraft's Version

This server is running WineSpigot version 1_8_R3 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

build 55

### Describe the bug

error in console

### To Reproduce

don't know except the plugin

### Additional Information

https://pastebin.com/P2Pnmuye

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
