### ISSUE TITLE
Power Axe Toolmode: Pillar

### ISSUE THREAD

**Issue by Bimmalord** [BG-Software-LLC/WildTools#218]
### Minecraft's Version

Version 1.21.1-R01.1-SNAPSHOT

### Plugin's Version

WildTools-2024.4-b62

### Describe the bug

Pillar mode not working in overworld trees and not working on nether trees

### To Reproduce

The Pillar mode does not work on Axe

### Additional Information

https://pastebin.com/gP1L68vW (the code from the plugin)

**Comment by OmerBenGera** [comment]
Check out latest dev build, this is fixed in latest dev build.

I recommend you to use `whitelisted-blocks` in general instead of blacklisting all the blocks in the game that are not wood logs. I also recommend you to enable `only-same-type`.

**Comment by Bimmalord** [comment]
Yeah but then you can break them with axe aswell and that's what i not
want, and the blocks that whitelisted they drop the blocks other blocks
don't drop. or you made it different in the config?

Op za 28 dec 2024 om 09:06 schreef Ome_R ***@***.***>:

**Comment by Bimmalord** [comment]
Fixed it only-same-type is now true and it works again thnx

Op zo 29 dec 2024 om 08:18 schreef Bimma lord ***@***.***>:
