### ISSUE TITLE
JobsReborn Hook

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/WildTools#47]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
Paper 1.8.8 latest 
**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
Latest on Jenkins (build-11) 
**Describe the bug**
JobsReborn support isn't working / option missing, I'm using a 3x3 trench pickaxe and I'm not gaining any exp & money from jobs reborn. 
**To Reproduce**
Steps to reproduce the bug.
Put jobs reborn on your server, join the miner job and mine with a trench pickaxe
**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.
Do not use the latest ver of jobs reborn use the build from October (31th) on spigotmc since the latest is broken and bugged.

**Comment by OmerBenGera** [comment]
Add JetsMinions to the other-plugins list.

**Comment by LuluxClient** [comment]
> JetsMinion

Still not working, here are my configs : 

Tool: https://pastebin.com/zATaKPhk
OtherPlugins : https://pastebin.com/aJ8JREz9

**Comment by OmerBenGera** [comment]
> 
> 
> > JetsMinion
> 
> Still not working, here are my configs :
> 
> Tool: https://pastebin.com/zATaKPhk
> OtherPlugins : https://pastebin.com/aJ8JREz9

Idk why I mentioned JetsMinion, I misread the issue.
Add "Jobs" to the other plugins list, as that's the name of your jobs plugin...
