### ISSUE TITLE
Tools lag

### ISSUE THREAD

**Issue by LeRoiDamien** [BG-Software-LLC/WildTools#48]
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
B11

Maysbe this spark could be a bit more revelant to you, before, I started spark sampler while my server was already lagging
https://spark.lucko.me/Cxzy5NSCSL

**Comment by OmerBenGera** [comment]
Take a timings report as well if possible.
The lag doesn't seem to come from WildTools, but due to the items that are dropped from blocks broken by the plugin. The lag seems to come when WildStacker tries to look for nearby items to stack. However, this lag happens when the plugin tries to get the location of other entities, so it might indicate about an overall lag on server, and therefore any small thing also lags.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by LeRoiDamien** [comment]
Good evening, sorry for the response time I had some personal concerns here are the timings to ask

https://timings.aikar.co/?id=cbeb39c7433045fda7c8eabd59028fac

**Comment by LeRoiDamien** [comment]
hello, So were you able to watch?

**Comment by OmerBenGera** [comment]
> 
> 
> hello, So were you able to watch?

Didn't notice anything special in the timings, sorry 0.0

**Comment by LeRoiDamien** [comment]
To say that by doing the timings I even managed to crash my server lol

**Comment by LeRoiDamien** [comment]
hello, so how can I do to avoid crash / lag?

**Comment by OmerBenGera** [comment]
> 
> 
> hello, so how can I do to avoid crash / lag?

What crash are you talking about?

**Comment by LeRoiDamien** [comment]
I'll make a video for you to be simpler ^^

**Comment by LeRoiDamien** [comment]
https://www.youtube.com/watch?v=GUtRw_64Xjs&ab_channel=RoiDamien


Here is when there are 3/4 players who do it at the same time the server crashes

**Comment by OmerBenGera** [comment]
Mind taking another spark profiler?

**Comment by OmerBenGera** [comment]
Wait, before that, update to latest version of WS.

**Comment by LeRoiDamien** [comment]
Now the items don't have time to stack

**Comment by LeRoiDamien** [comment]
the items are difficult to be sucked with the chest collector

**Comment by OmerBenGera** [comment]
The latest build of WS is broken

**Comment by LeRoiDamien** [comment]
Ok

**Comment by LeRoiDamien** [comment]
Always the same I do a spark?

**Comment by OmerBenGera** [comment]
don't take a spark profiler for now. Try build 128, it should work now

**Comment by LeRoiDamien** [comment]
ok i try

**Comment by LeRoiDamien** [comment]
at the beginning 0 lag then some block further the lag came

**Comment by OmerBenGera** [comment]
> 
> 
> at the beginning 0 lag then some block further the lag came

take a spark sampler then when the lag occurs

**Comment by LeRoiDamien** [comment]
https://spark.lucko.me/HkX6QO5qh5

**Comment by OmerBenGera** [comment]
> 
> 
> https://spark.lucko.me/HkX6QO5qh5

I don't see anything from WildTools, maybe take another spark profiler?

**Comment by OmerBenGera** [comment]
Hmm, the main issues that I see are the followings:
1) Dropping a lot of drops is a bit lagging the server
2) When harvesting the seeds, SSB a bit struggles with it, and I am gonna check it out

**Comment by LeRoiDamien** [comment]
keep me posted

**Comment by LeRoiDamien** [comment]
https://spark.lucko.me/eqWZhwwtPG
here is a spark that I just made

**Comment by OmerBenGera** [comment]
Try latest version of SSB

**Comment by LeRoiDamien** [comment]
Always the same :/

**Comment by OmerBenGera** [comment]
Take another spark profiler

**Comment by LeRoiDamien** [comment]
on each restart the SSB plugin breaks the upgrades the challenges the border ectect normal?

I make you spark now

**Comment by LeRoiDamien** [comment]
https://spark.lucko.me/KrwM3bvyMN

**Comment by LeRoiDamien** [comment]
Did you find something?

**Comment by OmerBenGera** [comment]
Ah yes, the lag seems to come from drops by WildTools.
Try blacklisting drops so they won't drop by the plugin

**Comment by LeRoiDamien** [comment]
Hi indeed with the drop blacklist there is 0 lag

**Comment by LeRoiDamien** [comment]
in many cases there is still a bit of lag

**Comment by LeRoiDamien** [comment]
but suddenly impossible to collect the drops 
:/

**Comment by OmerBenGera** [comment]
> 
> 
> but suddenly impossible to collect the drops
> :/

Yeah, that makes sense.
Let's see if I can do something about that.

**Comment by LeRoiDamien** [comment]
nice :;D

**Comment by OmerBenGera** [comment]
Check out latest dev build, hopefully it helps

**Comment by LeRoiDamien** [comment]
but suddenly the items are no longer dropped on the ground?

**Comment by OmerBenGera** [comment]
> but suddenly the items are no longer dropped on the ground?

Downgrade for now, I will check it out later

**Comment by LeRoiDamien** [comment]
Oh ok ^^

**Comment by LeRoiDamien** [comment]
Hello
Here is the config for the harvester, it is the last one with the name:

harvester_fortune3test

http://pastebin.fr/91726

**Comment by OmerBenGera** [comment]
Weird, it looks fine for me
Does it happen on another server with only WildTools installed on 1.16.5?

**Comment by LeRoiDamien** [comment]
Without any plugin there is no drop

**Comment by OmerBenGera** [comment]
Weird... I'll take a look at that next week, as I ran out of time for this day.

**Comment by LeRoiDamien** [comment]
there is no problem keep me informed ^^

**Comment by LeRoiDamien** [comment]
hello, I'm coming to the news :)

**Comment by LeRoiDamien** [comment]
hello, I'm coming to the news :)

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue, it works just fine for me.
Are you sure it doesn't work for you on a server with only WildTools installed with regular spigot?

**Comment by LeRoiDamien** [comment]
Still nothing here is a video for you to show

https://youtu.be/k_LiehifIrY

**Comment by LeRoiDamien** [comment]
on the other hand if I withdraw the auto collect it's perfect

**Comment by OmerBenGera** [comment]
I could replicate the issue with harvester hoes.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by LeRoiDamien** [comment]
nice it works now I will test with the players to see the lags

**Comment by LeRoiDamien** [comment]
still lags with several players but with only 1 player it's fine

https://spark.lucko.me/2wyhyviw4i

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be much better as I merge the items together before spawming them, causing much less items to actually be spawned.

**Comment by LeRoiDamien** [comment]
So that explains the fact that the items drop not often?

**Comment by LeRoiDamien** [comment]
Ever see?

**Comment by OmerBenGera** [comment]
> 
> 
> So that explains the fact that the items drop not often?

huh?

**Comment by OmerBenGera** [comment]
They will be dropped in stacks now, that's all

**Comment by LeRoiDamien** [comment]
I drop nothing at all when I pass the harvester

**Comment by LeRoiDamien** [comment]
or very rarely

**Comment by OmerBenGera** [comment]
Take a video please, as it works fine for me

**Comment by LeRoiDamien** [comment]
Here is

https://youtu.be/6fTBQqTp4FY

**Comment by OmerBenGera** [comment]
Any errors in console? Something?

**Comment by LeRoiDamien** [comment]
http://pastebin.fr/92271

**Comment by OmerBenGera** [comment]
Check out latest dev build

**Comment by LeRoiDamien** [comment]
For the moment it's very good I really thank you

**Comment by OmerBenGera** [comment]
> For the moment it's very good I really thank you

Let me know if it still lags your server

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by LeRoiDamien** [comment]
Hi no problem for the moment
