### ISSUE TITLE
Unknown error with WildTools

### ISSUE THREAD

**Issue by MinexusNetwork** [BG-Software-LLC/WildTools#52]
**Minecraft's Version**
git-Paper-626 (MC: 1.16.5)

**Plugin's Version**: -
WildTools-b12.jar

**Describe the bug**
When I first installed the plugin, it worked fine. I adjusted the tools to suit my needs and confirmed it was still working, this was a month ago. I haven't touched it since but players are now reporting that the sell wand I configured stopped working. I attempted to call on the plugin by executing the /tools give command and an error was thrown.

https://pastebin.com/ny6A6Jcg

**To Reproduce**
Steps to reproduce the bug.

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.

**Comment by OmerBenGera** [comment]
The plugin is disabled, therefore you can't execute its commands.
Look for the error that caused it to get disabled.

**Comment by MinexusNetwork** [comment]
Hi Omer,

I can't find the error causing this, when I restart my server. The console says below: (only these two lines, nothing else)

`16.05 12:20:50 [Server] INFO [WildTools] Enabling WildTools v2.10.4-DEVb12
16.05 12:20:50 [Server] INFO [WildTools] ******** ENABLE START ********`

Then once I log in and try to execute /tools I get an internal error occurred and the previously pasted pastebin console error.

**Comment by OmerBenGera** [comment]
Send me the entire logs file please via pastebin

**Comment by MinexusNetwork** [comment]
Here is the console: https://pastebin.com/wcfX1Zjs

Steps:
1) Restarted the server
2) Logged into server
3) Typed /tools

**Comment by OmerBenGera** [comment]
```16.05 12:46:46 [Server] INFO [WildTools] Enabling WildTools v2.10.4-DEVb12
16.05 12:46:46 [Server] INFO [WildTools] ******** ENABLE START ********
16.05 12:46:46 [Multicraft] Skipped 55 lines due to rate limit (30/s)```
Look in the logs file please, the Multicraft system just removed the errors from the console output.

**Comment by MinexusNetwork** [comment]
Sorry about that, please see logs now https://pastebin.com/DPgsY4kH

**Comment by OmerBenGera** [comment]
Show me your recipes file :)

**Comment by MinexusNetwork** [comment]
`####################################################
##                                                ##
##            WildTools Configuration             ##
##               Developed by Ome_R               ##
##                                                ##
####################################################

items:
  tool_core:
    type: REDSTONE
    name: '&4Tool Core'
    lore:
    - '&7You can craft tools with this core!'
    glow: true

recipes: []`

**Comment by MinexusNetwork** [comment]
```####################################################
##                                                ##
##            WildTools Configuration             ##
##               Developed by Ome_R               ##
##                                                ##
####################################################

items:
  tool_core:
    type: REDSTONE
    name: '&4Tool Core'
    lore:
    - '&7You can craft tools with this core!'
    glow: true

recipes: []```

**Comment by OmerBenGera** [comment]
Change `recipes: []` to `recipes: {}`

**Comment by MinexusNetwork** [comment]
Thank you very much! The plugin loaded fine and all is working again :)
