### ISSUE TITLE
crafting chest wand does not work Trench pick does not update lighting

### ISSUE THREAD

**Issue by SpeedRider** [BG-Software-LLC/WildTools#56]
**Minecraft's Version**
paper 1.16.5
git-paper-670

**Plugin's Version**: -
2.10.4 wild tools

**Describe the bug**
when adding the crafting recipe CHEST to the crafting wand the wand will no longer work and it can void items in the chest and will let the player open the chest that you right-clicked on to.

all so when using the pickaxe trench pickaxe and tray pickaxe it will not do lighting updates.
not sure if its just something to do with the server

**To Reproduce**
1st set a crafting wand to have a chest as one of the things it can craft. and use it on a chest.
2nd mine underground near torches and the light from the torches will not go into the new area.

**Additional information**
![2021-05-24_07 43 35](https://user-images.githubusercontent.com/17522328/119280411-e41fb700-bc63-11eb-9943-fc8e9cf4e94d.png)
![2021-05-24_07 43 44](https://user-images.githubusercontent.com/17522328/119280414-e6821100-bc63-11eb-8d9f-ed3b3477f0ba.png)
![2021-05-24_07 43 50](https://user-images.githubusercontent.com/17522328/119280416-e7b33e00-bc63-11eb-97f4-8845772ae2a4.png)

thank you for an amazing plugin so fun to make tools with and so nice :D

**Comment by OmerBenGera** [comment]
About lights, it's known and currently will not be fixed as it will cause more lag than actually being helpful.
About the crafting issues you talk about, mind give an example and a copy of your config (via pastebin)?

**Comment by OmerBenGera** [comment]
Any news regarding this?
