### ISSUE TITLE
Trench Pickaxe does not work on Purpur server

### ISSUE THREAD

**Issue by JblackMC** [BG-Software-LLC/WildTools#58]
**Minecraft's Version**
Purpur-1204 (MC: 1.17)

**Plugin's Version**: -
v2.11.0-DEVb20

**Describe the bug**
Trench pickaxes do not work. They work on sand. They do not work on stone and other "hard" blocks.

**To Reproduce**
1) Install plugin on fresh Purpur server.
2) Give yourself a trench pickaxe.
3) Go mine stone.

**Additional information**
Error in console: https://pastebin.com/1mKS61zw

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
