### ISSUE TITLE
Crafting wand issue

### ISSUE THREAD

**Issue by JHarris12345** [BG-Software-LLC/WildTools#59]
### Minecraft's Version

1.16.5 paper

### Plugin's Version

2.10.4

### Describe the bug

For a crafting wand (config for it below), it doesn't craft netherite ingots properly. It uses ALL the netherite scrap or ALL the gold ingots in a chest instead of what is needed. You fixed this already, I dont know why you unfixed it...?

`  netherite_wand_unlmt:
    tool-mode: CRAFTING
    type: STICK
    unbreakable: true
    name: '&f --{ &9&lNetherite Wand &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Hit a chest to craft netherite ingots from'
    - '&7 gold ingots and netherite scrap inside!'
    - '&f'
    - '&9&l Uses:'
    - '&fUnlimited'
    - '&f'
    - '&8&m---------------------------------------'
    craftings:
    - NETHERITE_INGOT`

### To Reproduce

Here's a gif... https://gyazo.com/f357c053e0358e6bc4bb1cc59cc8db77

Just place too much netherite scrap OR too much gold ingot, craft netherite ingots and it will use them all

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue.
Try using latest dev build

**Comment by JHarris12345** [comment]
Works fine on the dev build. Can you push to spigot please?

**Comment by OmerBenGera** [comment]
> 
> 
> Works fine on the dev build. Can you push to spigot please?

Spigot has a direct link to our official website where you can find all dev builds & stable builds in one place :)
