### ISSUE TITLE
Double Drop with AdvancedEnchantment

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/WildTools#62]
### Minecraft's Version

1.12.2

### Plugin's Version

WildTools-b21.jar

### Describe the bug

Hello, when i add AdvancedEnchantments into other-plugins section and break any block handle by advanced the plugin dupe the block

### To Reproduce

Install AdvancedEnchantments
Add auto smelt on item and break ore

**Comment by OmerBenGera** [comment]
AE should modify drops of blocks using the drops set in BlockBreakEvent, otherwise the plugins cannot work together.
