### ISSUE TITLE
FactionsUUID incompatibility bug

### ISSUE THREAD

**Issue by GerwinVerkerk** [BG-Software-LLC/WildTools#72]
### Minecraft's Version

1.17.1

### Plugin's Version

#26 23/10/2021 09:33:19

### Describe the bug

Using an tool in FactionsUUID territory doesn't work and raises console error:

https://paste.enginehub.org/0NKtCfe62

### To Reproduce

Claim land with FactionsUUID

Use wildtools in claimed territory with (use only inside claimed land on)

**Comment by OmerBenGera** [comment]
Vsrsion of FactionsUUID that you use?

**Comment by OmerBenGera** [comment]
Any news regarding this?
