### ISSUE TITLE
Trench Pickaxe doesn't work when upgraded to Netherite

### ISSUE THREAD

**Issue by GerwinVerkerk** [BG-Software-LLC/WildTools#73]
### Minecraft's Version

1.17.1

### Plugin's Version

#28 06/11/2021

### Describe the bug

When you upgrade your diamond trench tool to netherite using the smithing table, it no longer works.

### To Reproduce

See description

**Comment by OmerBenGera** [comment]
It seems to work fine for me using latest build of WildTools and on 1.17.1

**Comment by OmerBenGera** [comment]
Have you tried using latest build?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by GerwinVerkerk** [comment]
I think one of my players claims it is still broken. I haven't been able to test it myself yet. I will post an update once I do. Sorry for the deleyed reply.

**Comment by OmerBenGera** [comment]
All's good.
Let me know once you tested it yourself, as I can't seem to replicate the issue myself.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this for now.
If it still occurs, lmk.
