### ISSUE TITLE
Builders Wand

### ISSUE THREAD

**Issue by RedstoneGamer123** [BG-Software-LLC/WildTools#75]
### Minecraft's Version

1.12.2-Paper

### Plugin's Version

2.11.1-b30

### Describe the bug

It does not place the blocks nor take blocks out of my inventory. This is on SuperiorSkyblock-1.8.2

### To Reproduce

https://discord.com/channels/554276823010246687/554282655441747998/913070949660762113
All I am doing is trying to use the builder wand on my SuperiorSkyblock Island.

I tried to use an old version(2.10.2) in which I knew worked on SuperiorSkyblock-1.4.5, but after updating Superior it seems to have stopped working.

**Comment by OmerBenGera** [comment]
It happens because you have set only-inside-claim to true.
Set it to false and it should work again.

**Comment by RedstoneGamer123** [comment]
I've added [MCMMO](https://www.spigotmc.org/resources/official-mcmmo-classic.2445/) since last time: https://pastebin.com/4KRajWR8

Past that: https://youtu.be/FKtLR3qsj7Y

**Comment by OmerBenGera** [comment]
Seems like your mcmmo is outdated.
Are you using latest version of it for 1.12?

**Comment by RedstoneGamer123** [comment]
I am using the latest version of mcMMO-Classic for 1.12.2 as I am not paying for the revamp version.

**Comment by RedstoneGamer123** [comment]
and even without it that new video still happens the exact same.

**Comment by RedstoneGamer123** [comment]
Still happening with 2.11.1-b32

**Comment by OmerBenGera** [comment]
> Still happening with 2.11.1-b32 use-with-claim does nothing and without it, it still creates ghost blocks.

I havent fixed it, why would anything change?
Be patient.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
