### ISSUE TITLE
Insane TPS Drops Wildtools

### ISSUE THREAD

**Issue by GerwinVerkerk** [BG-Software-LLC/WildTools#78]
### Minecraft's Version

1.17.1

### Plugin's Version

#32 27/11/2021 19:48:55

### Describe the bug

Insane TPS drops when using harverster hoe. I don't know why this is happening. Running TNE economy. Wildtools is using essentials worth.yml for worth of blocks. 

### To Reproduce

https://timings.aikar.co/?id=0340a3fdde7e443590746445aac09777#plugins

**Comment by OmerBenGera** [comment]
Install spark plugin please, then run '/spark sampler' when you see TPS drop, wait a few seconds, then run `/spark sampler --stop` to stop. Send me the link that was generated.

**Comment by GerwinVerkerk** [comment]
https://spark.lucko.me/nmLpboXV3m

**Comment by GerwinVerkerk** [comment]
Made a better one:
https://timings.aikar.co/?id=8004001aeaca42c99c07298733aca29d
https://spark.lucko.me/ESj3aaMmLe

**Comment by OmerBenGera** [comment]
The lag comes from depositing money to your players.
Its due to your econony plugin and not WildTools.
Its shown as WildTools in the timings because it deposits the money, however nothing to do with the plugin.
