### ISSUE TITLE
Custom Models

### ISSUE THREAD

**Issue by Nathanspat08** [BG-Software-LLC/WildTools#79]
### Minecraft's Version

Paper 1.17.1

### Plugin's Version

1.17

### Describe the bug

Hi, I am building a Minecraft server, and I am trying to make custom models for the sell wand and harvesting hoe, is that possible to do?

### To Reproduce

.

### Additional Information

Thank you for helping!

**Comment by OmerBenGera** [comment]
Sadly no.
You are more than welcome to make a PR :)

**Comment by ElBananaa** [comment]
Hey!
I don't know if I should open a new issue since it's kinda related, but I was wondering if adding support for heads with a custom Base64 was planned or is already possible?
I tried, but didn't manage to get this working unfortunately :/

**Comment by OmerBenGera** [comment]
> 

It's not possible as far as I know.
No one asked for support for such thing yet, as most people don't use skulls as tools

**Comment by ElBananaa** [comment]
> > 
> 
> It's not possible as far as I know. No one asked for support for such thing yet, as most people don't use skulls as tools

I see, it's kinda sad, I'd love to see a such feature in the plugin but don't have enough knowledge to add it.
Anyways, thanks for the answer! :)
