### ISSUE TITLE
Duplicating glitch when RestrictedCreative is installed

### ISSUE THREAD

**Issue by InsaneTomas** [BG-Software-LLC/WildTools#80]
### Minecraft's Version

1.17.1

### Plugin's Version

latest 

### Describe the bug

Duplication of items ( With plugin restricte creative)

I dont know if this bug of wildtools or restricted creative :D 

### To Reproduce

1. go to /gmc ( https://www.spigotmc.org/resources/restrictedcreative.42790/ )
2. place blocks
3. go back to /gms
4. Break block with 3x3 
5. Duplicated!

### Additional Information

Restrictedcreative have api 

can be please fixed this? :D

**Comment by OmerBenGera** [comment]
What is RestrictedCreative?

**Comment by InsaneTomas** [comment]
Is the plugin for limited creattive

**Comment by OmerBenGera** [comment]
I will open a ticket for you in the weekend so you can send me a copy of their plugin jar so I can test it.

**Comment by InsaneTomas** [comment]
You have PM off and discord tickets i can´t

**Comment by OmerBenGera** [comment]
As I said, I will open one for you.
What is your discord?

**Comment by InsaneTomas** [comment]
IBadTomas is here#6503

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
Mind taking a video of the issue?

**Comment by OmerBenGera** [comment]
Check out latest dev build, I fixed a duplication glitch when breaking blocks below y0, might fix your issue as well.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, lmk
