### ISSUE TITLE
EconomyshopGUI Premium is not recognised

### ISSUE THREAD

**Issue by Tombspyder** [BG-Software-LLC/WildTools#81]
### Minecraft's Version

This server is running Paper version git-Paper-77 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5ad1d9a)
You are running the latest version
Previous version: git-Paper-73 (MC: 1.18.1)

### Plugin's Version

WildTools-2.11.1-b34 DEV

### Describe the bug

EconomyshopGUI Premium version is not recognised as a price setting in the config, despite it being listed. The non premium however seems to work,

### To Reproduce

Install EconomyshopGUI - premium and Wildtools on a server, change the configuration as appropriate. 

Wait for no price file to be found

**Comment by OmerBenGera** [comment]
If these are two different plugins and they dont share the same API, then the premium version may not work.
However, did WildTools registered EcononyShopGUI as the prices provider?

**Comment by Tombspyder** [comment]
It only registers it as a price provider on the free version, you may be right. They are two different plugins so there could be differences

**Comment by OmerBenGera** [comment]
What is your discord?
I will open a ticket for you so you can send me a copy of the plugin so I can add support for it.

**Comment by Tombspyder** [comment]
My discord is Amis#6726

Thanks again for the quick support!

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
