### ISSUE TITLE
Shopguiplus hook

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/WildTools#82]
### Minecraft's Version

1.12.2

### Plugin's Version

b43

### Describe the bug

Hello, with the new version the hook with shopguiplus not works with sell mode.

### To Reproduce

Use ShopGUIPlus-1.68.1 and WT b43 and try to sell anything in a chest, the plugin will say : "Nothing to sell"

**Comment by nivcoo** [comment]
I've chekc my console and i've : [Server thread/INFO]: Using ShopGUIPlus as a prices provider. so i think the plugin hook shopgui but not works correctly

**Comment by OmerBenGera** [comment]
Use latest stable build, let me know if it works

**Comment by nivcoo** [comment]
> Use latest stable build, let me know if it works

I already use the latest build (b43 Version 2.11.3)

**Comment by nivcoo** [comment]
I've back to #36 and it works

**Comment by OmerBenGera** [comment]
I will look into it.

**Comment by TenReeez** [comment]
Im having same issue. I use economyshopgui and it says "there was no items to sell" when i hit chest with sellwand

1.18.1 paper
wildtools version 2.11.3

**Comment by OmerBenGera** [comment]
I tested the ShopGUIPlus hook and it works fine for me.

**Comment by nivcoo** [comment]
Not for me, it doesn't works after the build #38

**Comment by OmerBenGera** [comment]
> Not for me, it doesn't works after the build #38

It works fine.
Try it on a server with only WT installed and SGP
Make sure you have SGP configured as your prices provider in the config file.

**Comment by nivcoo** [comment]
> > Not for me, it doesn't works after the build #38
> 
> It works fine. Try it on a server with only WT installed and SGP Make sure you have SGP configured as your prices provider in the config file.

**Comment by nivcoo** [comment]
Sorry x), i will try but i doin't understand why it works before. I have SS2 and WS and WL also

**Comment by TenReeez** [comment]
I have set up a test server. With only Wildtools, Vault and economyshopgui.  prices-plugin: economyshopgui
When i click on chest it says vault is not installed. 
If i add essentials, i dont get that error msg but it says nothing to sell in chest.
I disabled everything except wildtools and Vault, in wildtools config had:  prices-plugin: Wildtools
and still get Vault not installed. This msg only goes away after essentials installed.
Any ideas on your end Omer?

**Comment by TenReeez** [comment]
Omer I have tried Build #36 wildtools. I dont have an issue selling, it works.
Its only happening on later wildtool builds.

**Comment by TenReeez** [comment]
I dont understand why everything works on build #36, but when i changed to latest Wildtools build, Wildtools has stopped working with other plugins

**Comment by nivcoo** [comment]
> I dont understand why everything works on build #36, but when i changed to latest Wildtools build, Wildtools has stopped working with other plugins

Me too

**Comment by OmerBenGera** [comment]
Are you trying it on a double chest maybe?

**Comment by TenReeez** [comment]
no just single. The only difference is wildtools versions

**Comment by OmerBenGera** [comment]
@nivcoo @TenReeez Should be fixed in latest dev build. Let me know if it works for you as well.

**Comment by OmerBenGera** [comment]
I am closing this as it's fixed in my testings.
Let me know if it isn't for no reason
