### ISSUE TITLE
McMMO Hook

### ISSUE THREAD

**Issue by TenReeez** [BG-Software-LLC/WildTools#83]
### Minecraft's Version

1.18.1-R0.1-snapshot Paper

### Plugin's Version

2.11.3 wildtools

### Describe the bug

Getting the following message in console:
https://pastebin.com/5r617zzT

I am not sure where and what the error 
com.bgsoftware.wildtools.hooks.McMMOHook.MCMMO_PLACESTORE_SET" is null means.

Do I add - MCMMO to
 # A list of all the other plugins that needs to know about breaking of blocks.
  # You can add your custom shops plugins, spawners plugin and more.
  # WildTools will not care if events are cancelled from this list. Therefore, if WildTools needs to know
  # if the events are cancelled from a plugin, add it to the 'claiming-plugins' section.
  other-plugins: []

in the wild tools config?

thankyou

### To Reproduce

Use the current version supplied

### Additional Information

I am using an old config file, but latest build

**Comment by OmerBenGera** [comment]
Version of McMMO?

**Comment by TenReeez** [comment]
Not the latest one. 

I will update to the latest mcmmo version on reboot and let you know asap. ( 12 hours)

**Comment by OmerBenGera** [comment]
@TenReeez ?

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
