### ISSUE TITLE
Infinite sugar cane glitch with harverster tool

### ISSUE THREAD

**Issue by GerwinVerkerk** [BG-Software-LLC/WildTools#84]
### Minecraft's Version

Previous version: git-Paper-101 (MC: 1.18.1)

### Plugin's Version

[21:44:37 INFO]: WildTools version 2.11.1.34
[21:44:37 INFO]: Configurable trench picks, tray picks, sell-wands, harvester-hoes and more!
[21:44:37 INFO]: Website: https://bg-software.com/
[21:44:37 INFO]: Author: Ome_R

### Describe the bug

You can get infinite sugarcane when using the harverster hoe, it also seems to work on bamboo

### To Reproduce

Check video:

https://youtu.be/SidK4m2WNG0

### Additional Information

SEE VIDEO ABOVE

**Comment by OmerBenGera** [comment]
Are there any errors in console?

**Comment by GerwinVerkerk** [comment]
I can't confirm but I believe there are not

**Comment by OmerBenGera** [comment]
> I can't confirm but I believe there are not

Are you able to replicate the issue on another server with only WT installed?

**Comment by Skizzles** [comment]
@GerwinVerkerk any response to the above?
