### ISSUE TITLE
Builder Wand Not Placing correct number of blocks

### ISSUE THREAD

**Issue by Hyrulez** [BG-Software-LLC/WildTools#86]
### Minecraft's Version

Paper 1.17.1 build#399

### Plugin's Version

WildTools Dev build #45

### Describe the bug

Upon trying to use a builders wand, It will place only a single block instead of what it is configured to in the config. Currently my config is set to 5 blocks and it will only place 1. At certain points it will spawn in glitched invisible blocks. If you leave the chunks and come back the glitched blocks will become visible again however not in a full pillar. There are no errors in console when using the tools nor upon startup. I feel the need to specify that it only places one block regardless of the block, and the number of blocks in the players inventory

### To Reproduce

Use the builders wand

### Additional Information

[latest (1).log](https://github.com/BG-Software-LLC/WildTools/files/7805452/latest.1.log)
[config.txt](https://github.com/BG-Software-LLC/WildTools/files/7805458/config.txt)

**Comment by OmerBenGera** [comment]
Are you able to replicate the issue on another server with only WildTools installed?

**Comment by Skizzles** [comment]
@Hyrulez Any response to the above?
