### ISSUE TITLE
McMMO Dupe

### ISSUE THREAD

**Issue by SlimeCody** [BG-Software-LLC/WildTools#96]
### Minecraft's Version

1.18.1 git-paper-144 Paper

### Plugin's Version

WildTools 2.12,0
McMMO 2.1.211

### Describe the bug

Using the pillar wand, MCMMO doesnt seem to be receiving the data that those blocks are placed by the user.

### To Reproduce

Use a pillar wand on cobblestone/ores. Break with a pickaxe, and it has a chance to double.

### Additional Information

I know this has happened in the past and Ome_R was quick to resolve it. By reverting 2 McMMO versions it fixes it but in that previous version there is a bug with one of the skills.

**Comment by OmerBenGera** [comment]
Add McMMO to the other-plugins list on your config file.

**Comment by SlimeCody** [comment]
I have had this in the configuration for the plugin for as long as I can remember that does not resolve the issue. As I stated it works correctly with a different version of mcmmo.

**Comment by OmerBenGera** [comment]
They might have changed the way blocks are tracked.
In which version of mcMMO did it start to occur?
Also, are you able to find the commit that broke it?

**Comment by SlimeCody** [comment]
It works on McMMO Version 2.1.209
It doesnt work on McMMO Version 2.1.211

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
