### ISSUE TITLE
Paper's anti-xray integration causing errors

### ISSUE THREAD

**Issue by ItzFabb-uwu** [BG-Software-LLC/WildTools#98]
### Minecraft's Version

1.18.1 PaperMc

### Plugin's Version

2.12.0 Build 54

### Describe the bug

Wildtools still having an issue to gencubes whenever i mined a block wildtools Throw a bunch of error :(

### To Reproduce

-/gc give YourName example1 1
-/tools give YourName <pickaxe> 1
- place the gencubes and mine it with the pickaxe from wildtools, it throws error!

### Additional Information

None

**Comment by ItzFabb-uwu** [comment]
[latest.log](https://github.com/BG-Software-LLC/WildTools/files/8348996/latest.log)

**Comment by ItzFabb-uwu** [comment]
`####################################################
##                                                ##
##            WildTools Configuration             ##
##               Developed by Ome_R               ##
##                                                ##
####################################################

# Choose which prices plugin to check for prices (ShopGUIPlus, Essentials, CMI, newtShop, QuantumShop, EconomyShopGUI, WildTools).
prices-plugin: 'ShopGUIPlus'

# Path to the logs file.
# You may disable it by setting the path to be empty.
logs-file: 'logs.txt'

# A list of prices. Use "TYPE" and "TYPE:DATA" formats.
prices-list:
- 'STONE:5' #Each stone will cost $5
- 'LOG:0:5' #Only oak logs will cost $5

# Here you can configure which plugins will be called, etc.
# Optimizing the lists will result better performance!
events-manipulations:
  # A list of all the plugins that handle claims here on your server.
  # If one of the plugins here cancel the events, then WT will know that the player doesn't have access.
  claiming-plugins:
    - EXAMPLE_PLUGIN
  # A list of all the other plugins that needs to know about breaking of blocks.
  # You can add your custom shops plugins, spawners plugin and more.
  # WildTools will not care if events are cancelled from this list. Therefore, if WildTools needs to know
  # if the events are cancelled from a plugin, add it to the 'claiming-plugins' section.
  other-plugins:
    - 'GenCubes'`

**Comment by OmerBenGera** [comment]
Upload logs to pastebin and send it here please.

**Comment by ItzFabb-uwu** [comment]
> Upload logs to pastebin and send it here please.

ok moment

**Comment by ItzFabb-uwu** [comment]
https://pastebin.com/Hd6ASEnP

**Comment by OmerBenGera** [comment]
The issue is not related to Gencubes, it's a bug with the plugin and integration with the anti-xray of Paper.
What version of Paper exactly are you using? (exact output from /version)

**Comment by ItzFabb-uwu** [comment]
[12:14:35] [Thread-55/INFO]: This server is running Paper version git-Paper-"91f3eda" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 91f3eda)
You are 253 version(s) behind
Previous version: git-Paper-"b9f26bb" (MC: 1.18.2)

**Comment by OmerBenGera** [comment]
Please upload your paper's config file to pastebin and send it here.
I can't seem to replicate it on my end.

**Comment by ItzFabb-uwu** [comment]
https://pastebin.com/PSXpzn8P

**Comment by OmerBenGera** [comment]
It works fine for me using your config as well, which makes me thing it's something related to the version you use. I am using:
```
[15:42:42 INFO]: Checking version, please wait...
[15:42:42 INFO]: This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)
You are 29 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-225 (MC: 1.18.2)
```

Try updating, let me know if it fixes itself for you.

**Comment by ItzFabb-uwu** [comment]
Can you able to send me your papermc jar?

**Comment by OmerBenGera** [comment]
> Can you able to send me your papermc jar?

Download latest one for 1.18.1 from the official site.

**Comment by ItzFabb-uwu** [comment]
I did and that's the latest one build #216

**Comment by ItzFabb-uwu** [comment]
https://papermc.io/api/v2/projects/paper/versions/1.18.1/builds/216/downloads/paper-1.18.1-216.jar

**Comment by OmerBenGera** [comment]
Works fine for me.

**Comment by ItzFabb-uwu** [comment]
a gencube right with wildtools?

**Comment by ItzFabb-uwu** [comment]
im having a headache, and i dont know what the heck am i doing

**Comment by ItzFabb-uwu** [comment]
https://polymart.org/resource/gencubes.1582#!

**Comment by OmerBenGera** [comment]
> a gencube right with wildtools?

Does it only happen if you have gencube installed?

**Comment by OmerBenGera** [comment]
> Yes! it is, im combining gencubes with wildtools and it throws that error

I suspect that they somehow interface with Paper's anti xray.
Try asking them what they are doing or what may cause the errors.
You can send them the link for this issue so they can comment here :)

**Comment by OmerBenGera** [comment]
I myself do not have access to Gencubes and therefore I can't test it myself.

**Comment by ItzFabb-uwu** [comment]
> I myself do not have access to Gencubes and therefore I can't test it myself.

So is there a way to fix this :[?

**Comment by ItzFabb-uwu** [comment]
> > Yes! it is, im combining gencubes with wildtools and it throws that error
> 
> I suspect that they somehow interface with Paper's anti xray. Try asking them what they are doing or what may cause the errors. You can send them the link for this issue so they can comment here :)

i swear i didnt see this but okay anyway goodnight ill ask him tommorow

**Comment by OmerBenGera** [comment]
> > > Yes! it is, im combining gencubes with wildtools and it throws that error
> > 
> > 
> > I suspect that they somehow interface with Paper's anti xray. Try asking them what they are doing or what may cause the errors. You can send them the link for this issue so they can comment here :)
> 
> i swear i didnt see this but okay anyway goodnight ill ask him tommorow

Hey, have you looked into it?

**Comment by ItzFabb-uwu** [comment]
yup its fixed and it was supsb2
