### ISSUE TITLE
ShopGuiPlus Error

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/WildTools#99]
### Minecraft's Version

1.16.5 using paper-1.16.5-794

### Plugin's Version

WildTools-2.12.0-b54.jar

### Describe the bug

Trying to sell items using the sellwand1 in a double with an item that's in shopguiplus. When I try to sell I get this error in the console which you can find this error here https://pastebin.com/kbK9emEB. I hope you can fix it.

### To Reproduce

Place a double chest, with a stack of diamonds and try sell using the sellwand1

**Comment by OmerBenGera** [comment]
Downgrade SGP for now

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
